Repository bpg/terraform-provider-proxmox, pull requests merged in 2022-12, with the labels that each got.

#175 fix: Remove cloned ide2 before creating new one (#174)
  example/resource_virtual_environment_vm.tf
  proxmoxtf/resource_virtual_environment_vm.go
Labels: go, size: s

#180 fix: handling `datastore_id` in LXC template
  example/resource_virtual_environment_container.tf
  proxmoxtf/resource_virtual_environment_container.go
Labels: go, size: s, autoapprove

#182 fix: Check if any interface has global unicast address instead of all interfaces
  example/resource_virtual_environment_vm.tf
  proxmox/virtual_environment_vm.go
Labels: go, size: s

#178 feat: add the ability to clone to non-shared storage on different nodes
  docs/resources/virtual_environment_vm.md
  proxmox/virtual_environment_datastores.go
  proxmox/virtual_environment_datastores_types.go
  proxmox/virtual_environment_vm.go
  proxmox/virtual_environment_vm_types.go
  proxmoxtf/resource_virtual_environment_vm.go
  proxmoxtf/utils.go
Labels: go, size: m

#181 feat: add support for "ssd" disk flag for VM
  docs/resources/virtual_environment_vm.md
  example/resource_virtual_environment_vm.tf
  proxmox/virtual_environment_vm_types.go
  proxmox/virtual_environment_vm_types_test.go
  proxmoxtf/resource_virtual_environment_vm.go
Labels: go, size: m

#176 feat: add support for network_device MTU
  docs/resources/virtual_environment_container.md
  docs/resources/virtual_environment_vm.md
  example/resource_virtual_environment_container.tf
  example/resource_virtual_environment_vm.tf
  proxmox/virtual_environment_vm_types.go
  proxmoxtf/resource_virtual_environment_container.go
  proxmoxtf/resource_virtual_environment_container_test.go
  proxmoxtf/resource_virtual_environment_vm.go
  proxmoxtf/resource_virtual_environment_vm_test.go
Labels: go, size: m

#194 feat: Add `hostpci` support
  docs/resources/virtual_environment_vm.md
  proxmox/virtual_environment_vm_types.go
  proxmoxtf/resource_virtual_environment_vm.go
  proxmoxtf/resource_virtual_environment_vm_test.go
  proxmoxtf/utils.go
Labels: documentation, go, autoapprove, size: l

#196 feat: Deletion of VM also purges all storages and configs
  proxmox/virtual_environment_vm.go
Labels: go, size: xs, autoapprove

#191 feat(vm): OnBoot: change default to `true`
  docs/resources/virtual_environment_vm.md
  proxmoxtf/resource_virtual_environment_vm.go
Labels: documentation, size: xs, markdown
