Repository bpg/terraform-provider-proxmox, pull requests merged in 2023-09, with the labels that each got.

#533 fix(node): file upload in multi-node PVE cluster
  proxmox/nodes/tasks/client.go
  proxmox/nodes/tasks/tasks.go
  proxmox/nodes/tasks/tasks_types.go
  proxmox/nodes/tasks/tasks_types_test.go
Labels: autoapprove, size/L

#520 feat(provider): add optional SSH port param to node in provider ssh block
  docs/index.md
  internal/provider/provider.go
  proxmox/ssh/client.go
  proxmox/ssh/resolver.go
  proxmoxtf/provider/provider.go
  proxmoxtf/provider/schema.go
Labels: size/M

#536 chore(code): fix `proxmox` package dependencies
  internal/cluster/datasource_haresource.go
  internal/cluster/datasource_haresources.go
  internal/cluster/haresource_model.go
  internal/cluster/resource_haresource.go
  internal/network/resource_linux_bridge.go
  internal/network/resource_linux_vlan.go
  internal/structure/attribute.go
  internal/validators/ha_resource_validator.go
  proxmox/access/acl_types.go
  proxmox/access/roles.go
  proxmox/access/roles_types.go
  proxmox/access/users.go
  proxmox/access/users_types.go
  proxmox/api/ticket_auth_types.go
  proxmox/cluster/cluster_types.go
  proxmox/cluster/firewall/options_types.go
  proxmox/cluster/ha/groups/hagroups_types.go
  proxmox/cluster/ha/resources/resources.go
  proxmox/cluster/ha/resources/resources_types.go
  proxmox/firewall/ipset_types.go
  proxmox/firewall/options_types.go
  proxmox/firewall/rules.go
  proxmox/nodes/certificate_types.go
  proxmox/nodes/containers/containers_types.go
  proxmox/nodes/network_types.go
  proxmox/nodes/nodes_types.go
  proxmox/nodes/storage_types.go
  proxmox/nodes/vms/vms_types.go
  proxmox/nodes/vms/vms_types_test.go
  proxmox/pools/pool_types.go
  proxmox/storage/storage_types.go
  proxmox/types/common_types.go
  proxmox/types/disk_size.go
  proxmox/types/disk_size_test.go
  proxmox/types/ha_resource_id.go
  proxmox/types/ha_resource_id_test.go
  proxmox/types/ha_resource_state.go
  proxmox/types/ha_resource_state_test.go
  proxmox/types/ha_resource_type.go
  proxmox/types/ha_resource_type_test.go
  proxmox/types/helpers.go
  proxmoxtf/resource/certificate.go
  proxmoxtf/resource/cluster/firewall/firewall.go
  proxmoxtf/resource/container.go
  proxmoxtf/resource/firewall/ipset.go
  proxmoxtf/resource/firewall/options.go
  proxmoxtf/resource/firewall/rules.go
  proxmoxtf/resource/group.go
  proxmoxtf/resource/role.go
  proxmoxtf/resource/user.go
  proxmoxtf/resource/validator/file.go
  proxmoxtf/resource/vm.go
Labels: autoapprove, size/XXL

#537 feat(lxc): add support for `keyctl` and `fuse` features
  docs/resources/virtual_environment_container.md
  proxmoxtf/resource/container.go
  proxmoxtf/resource/container_test.go
Labels: size/M

#545 fix(provider): panic crash in provider, interface conversion error
  proxmoxtf/provider/provider.go
Labels: size/XS

#546 fix(vm): explicitly allow `""` as a value for CloudInit interfaces
  proxmoxtf/resource/validator/vm.go
  proxmoxtf/resource/vm.go
Labels: size/S

#543 feat(file): FORMAT CHANGE: update import id, so it matches the resource's format: `<node_name>/<datastore_id>:<content_type>/<file>`
  docs/resources/virtual_environment_file.md
  proxmoxtf/resource/file.go
  proxmoxtf/resource/file_test.go
Labels: autoapprove, size/L

#549 chore(ci): cleanup and update project configs
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/semgrep.yml
  .github/workflows/test.yml
  Makefile
Labels: autoapprove, size/M

#548 feat(cluster): add cluster options resource
  docs/data-sources/virtual_environment_hagroup.md
  docs/data-sources/virtual_environment_hagroups.md
  docs/data-sources/virtual_environment_haresource.md
  docs/data-sources/virtual_environment_haresources.md
  docs/resources/virtual_environment_cluster_options.md
  docs/resources/virtual_environment_hagroup.md
  docs/resources/virtual_environment_haresource.md
  example/resource_virtual_environment_cluster_options.tf
  examples/resources/proxmox_virtual_environment_cluster_options/import.sh
  examples/resources/proxmox_virtual_environment_cluster_options/resource.tf
  internal/cluster/resource_options.go
  internal/provider/provider.go
  internal/structure/attribute.go
  internal/test/cluster/cluster_options_test.go
  internal/validators/i18n.go
  proxmox/cluster/options.go
  proxmox/cluster/options_types.go
  tools/tools.go
Labels: size/XXL

#561 chore(deps): bump github.com/hashicorp/terraform-plugin-* dependencies
  go.mod
  go.sum
Labels: dependencies, autoapprove, size/M

#563 fix(lxc,vm): error unmarshalling string `cpulimit`
  proxmox/nodes/containers/containers_types.go
  proxmox/nodes/vms/vms_types.go
Labels: autoapprove, size/XS

#564 chore(code): remove redundant `types2` import aliases
  proxmox/cluster/ha/resources/resources.go
  proxmox/cluster/ha/resources/resources_types.go
  proxmox/nodes/containers/containers_types.go
  proxmox/nodes/vms/vms_types.go
  proxmox/nodes/vms/vms_types_test.go
  proxmoxtf/resource/container.go
  proxmoxtf/resource/vm.go
Labels: autoapprove, size/XXL

#568 chore(code): re-organize and cleanup "fwk provider"'s code
  Makefile
  docs/resources/virtual_environment_container.md
  fwprovider/datasource_hagroup.go
  fwprovider/datasource_hagroups.go
  fwprovider/datasource_haresource.go
  fwprovider/datasource_haresources.go
  fwprovider/datasource_version.go
  fwprovider/hagroup_model.go
  fwprovider/haresource_model.go
  fwprovider/provider.go
  fwprovider/resource_hagroup.go
  fwprovider/resource_haresource.go
  fwprovider/resource_linux_bridge.go
  fwprovider/resource_linux_vlan.go
  fwprovider/resource_options.go
  fwprovider/structure/attribute.go
  fwprovider/tests/datasource_version_test.go
  fwprovider/tests/resource_linux_bridge_test.go
  fwprovider/tests/resource_linux_vlan_test.go
  fwprovider/tests/resource_options_test.go
  fwprovider/tests/test_support.go
  fwprovider/types/ip_addr.go
  fwprovider/types/ip_addr_test.go
  fwprovider/types/ip_addr_value.go
  fwprovider/types/ip_cidr.go
  fwprovider/types/ip_cidr_test.go
  fwprovider/types/ip_cidr_value.go
  fwprovider/validators/ha_resource_validator.go
  fwprovider/validators/i18n.go
  fwprovider/validators/parse_validator.go
  go.mod
  go.sum
  internal/internal.go
  internal/test/network/resource_linux_bridge_test.go
  internal/test/network/resource_linux_vlan_test.go
  main.go
  proxmox/nodes/network.go
  proxmox/nodes/vms/vms.go
  proxmoxtf/resource/validator/vm.go
  proxmoxtf/resource/validator/vm_test.go
  proxmoxtf/resource/vm.go
  proxmoxtf/resource/vm_test.go
  proxmoxtf/structure/schema.go
Labels: autoapprove, size/XL

#572 fix(network): remove computed flag from mtu attribute
  docs/resources/virtual_environment_network_linux_bridge.md
  fwprovider/resource_linux_bridge.go
  fwprovider/resource_linux_vlan.go
  fwprovider/tests/resource_linux_bridge_test.go
  fwprovider/tests/resource_linux_vlan_test.go
Labels: autoapprove, size/M

#574 chore(doc): add a note about DCO to CONTRIBUTING.md
  CONTRIBUTING.md
Labels: autoapprove, size/S

#576 misc: Sign-off release-please commits
  .github/workflows/release-please.yml
Labels: autoapprove, size/XS

#580 chore(docs): update `proxmox_virtual_environment_file` documentation
  docs/resources/virtual_environment_file.md
Labels: size/XS

#582 misc: fix Sign-off release-please commits
  .github/workflows/release-please.yml
Labels: autoapprove, size/XS

#583 chore(docs): add "Proof of Work" section to the PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: autoapprove, size/XS

#585 chore(code): bump go to v1.21
  README.md
  go.mod
  go.sum
  tools/go.mod
  tools/go.sum
Labels: autoapprove, size/M

#573 fix(cluster): inconsistencies in applying cluster options
  docs/resources/virtual_environment_cluster_options.md
  fwprovider/resource_options.go
  fwprovider/tests/resource_options_test.go
  proxmox/types/common_types.go
Labels: autoapprove, size/L

#591 fix(tasks): fix UPID (task id) parsing error
  proxmox/nodes/tasks/tasks_types.go
  proxmox/nodes/tasks/tasks_types_test.go
Labels: autoapprove, size/M

#593 feat(file): add optional `overwrite` flag to the file resource
  docs/resources/virtual_environment_file.md
  fwprovider/tests/resource_file_test.go
  proxmoxtf/resource/file.go
Labels: autoapprove, size/L
