Repository bpg/terraform-provider-proxmox, pull requests merged in 2023-05, with the labels that each got.

#317 chore(make): Add `lint`, `release-build` targets
  Makefile
Labels: autoapprove, size/S

#319 fix(vm): Fix IPv6 handling
  example/resource_virtual_environment_vm.tf
  proxmoxtf/resource/vm.go
Labels: size/S

#322 fix(vm,lxc): Tags reordering on plan re-apply
  proxmoxtf/resource/container.go
  proxmoxtf/resource/utils.go
  proxmoxtf/resource/vm.go
Labels: autoapprove, size/M

#326 feat(vm,lxc): Improved support for different disk size units
  proxmox/types/common_types.go
  proxmox/types/disk_size.go
  proxmox/types/disk_size_test.go
  proxmox/types/helpers.go
  proxmox/utils.go
  proxmox/utils_test.go
  proxmox/virtual_environment_container_types.go
  proxmox/virtual_environment_vm_types.go
  proxmox/virtual_environment_vm_types_test.go
  proxmoxtf/resource/container.go
  proxmoxtf/resource/vm.go
Labels: size/L

#330 fix(vm,lxc): Add validation for non-empty tags
  proxmoxtf/resource/container.go
  proxmoxtf/resource/vm.go
Labels: autoapprove, size/S

#335 fix(vm): Regression: cannot create disks larger than 99G
  proxmox/types/disk_size.go
  proxmox/types/disk_size_test.go
Labels: autoapprove, size/M

#342 feat: bump Go to 1.20 to resolve MacOS DNS resolution issues
  Makefile
  README.md
  go.mod
  tools/go.mod
Labels: size/XS

#345 fix(vm): Regression: wait for 'net.IsGlobalUnicast' IP address (#100)
  proxmox/virtual_environment_vm.go
Labels: size/XS

#350 feat(core): Add API Token authentication
  docs/Gemfile.lock
  docs/index.md
  proxmox/api/authentication.go
  proxmox/api/client.go
  proxmox/api/credentials.go
  proxmox/api/ticket_auth.go
  proxmox/api/ticket_auth_types.go
  proxmox/api/token_auth.go
  proxmoxtf/provider/provider.go
  proxmoxtf/provider/schema.go
Labels: autoapprove, size/XL
