Repository bpg/terraform-provider-proxmox, pull requests merged in 2023-03, with the labels that each got.

#251 feat(lxc): Add option for nested container feature
  docs/resources/virtual_environment_container.md
  proxmoxtf/resource_virtual_environment_container.go
  proxmoxtf/resource_virtual_environment_container_test.go
Labels: documentation, go, size: m

#254 frat(vm): Add custom CPU models support
  proxmoxtf/utils.go
  proxmoxtf/utils_test.go
Labels: go, size: s

#259 fix(vm): Fix `file_format` setting for new empty disks
  proxmox/virtual_environment_vm_types.go
  proxmoxtf/resource_virtual_environment_vm.go
Labels: go, size: xs, autoapprove

#262 fix(build): Fix make example-init for TF 1.4
  .github/workflows/test.yml
  Makefile
  example.tfrc
  example/versions.tf
Labels: size: s, autoapprove

#266 chore(docs): Minor documentation Improvements
  docs/index.md
  docs/resources/virtual_environment_vm.md
Labels: documentation, markdown, size: s, autoapprove

#267 chore: additional logging in API client
  proxmox/virtual_environment_authentication.go
  proxmox/virtual_environment_client.go
Labels: go, size: s, autoapprove

#268 feat(vm): Add bare minimum VM datasource
  docs/_config.yml
  docs/data-sources/virtual_environment_vm.md
  docs/data-sources/virtual_environment_vms.md
  example/data_source_virtual_environment_vm.tf
  example/data_source_virtual_environment_vms.tf
  go.mod
  go.sum
  proxmox/virtual_environment_vm.go
  proxmox/virtual_environment_vm_types.go
  proxmoxtf/data_source_virtual_environment_vm.go
  proxmoxtf/data_source_virtual_environment_vm_test.go
  proxmoxtf/data_source_virtual_environment_vms.go
  proxmoxtf/data_source_virtual_environment_vms_test.go
  proxmoxtf/provider.go
Labels: documentation, go, autoapprove, size: l

#280 feat: Update to Go 1.19
  .github/workflows/golangci-lint.yml
  .github/workflows/publish.yml
  .github/workflows/test.yml
  README.md
  go.mod
  tools/go.mod
Labels: go, autoapprove, size/M
