Repository bpg/terraform-provider-proxmox, pull requests merged in 2023-02, with the labels that each got.

#223 fix(vm): Don't add an extra hostpci entry
  proxmoxtf/resource_virtual_environment_vm.go
Labels: go, size: s

#227 chore: disable code coverage
  .github/workflows/test.yml
Labels: autoapprove

#225 feat(lxc): Add unprivileged option
  docs/resources/virtual_environment_container.md
  proxmoxtf/resource_virtual_environment_container.go
  proxmoxtf/resource_virtual_environment_container_test.go
Labels: documentation, go, size: s, api: container

#228 fix(vm): Fix handling of empty kvm arguments
  proxmoxtf/resource_virtual_environment_vm.go
Labels: go, size: xs, autoapprove

#231 fix(vm): ignore ssd disk flag with virtio interface
  proxmoxtf/resource_virtual_environment_vm.go
Labels: go, size: xs

#233 fix(build): trailing space in provider's version
  Makefile
Labels: size: xs, autoapprove

#240 fix(vm): `proxmox_virtual_environment_file.changed` stored as `true` at file creation
  proxmoxtf/resource_virtual_environment_file.go
Labels: go, size: xs, autoapprove

#241 feat(vm): update VM disc import logic
  example/resource_virtual_environment_vm.tf
  proxmox/virtual_environment_nodes.go
  proxmoxtf/resource_virtual_environment_vm.go
Labels: go, size: s, autoapprove

#242 chore(deps): bump dependencies
  go.mod
  go.sum
Labels: size: m, autoapprove
