Repository bpg/terraform-provider-proxmox, pull requests merged in 2023-06, with the labels that each got.

#354 fix(vm): Make mac_address computed, fix #339
  proxmoxtf/resource/vm.go
Labels: size/S

#355 feat(v): Add ability to override node IP used for SSH connection
  docs/index.md
  proxmox/api/authenticator.go
  proxmox/api/client.go
  proxmox/api/client_types.go
  proxmox/ssh/client.go
  proxmox/ssh/client_types.go
  proxmox/ssh/resolver.go
  proxmoxtf/provider/provider.go
  proxmoxtf/provider/schema.go
  proxmoxtf/resource/file.go
  proxmoxtf/resource/vm.go
Labels: autoapprove, size/L

#356 chore(doc): project documentation update
  CONTRIBUTING.md
  README.md
  docs/index.md
Labels: autoapprove, size/M

#359 fix(firewall): Improve firewall resources argument validation
  proxmoxtf/resource/firewall/selector.go
Labels: autoapprove, size/S

#365 fix(vm): fix incorrect disk interface ref when reading VM info from PVE
  proxmoxtf/resource/utils.go
  proxmoxtf/resource/vm.go
Labels: autoapprove, size/S

#366 fix(docs): Update documentation for resource `proxmox_virtual_environment_firewall_ipset`
  docs/resources/virtual_environment_firewall_ipset.md
Labels: size/XS, automerge

#369 fix(core): Do not limit cluster size to 1 in provider's `ssh` config
  proxmoxtf/provider/provider_test.go
  proxmoxtf/provider/schema.go
  proxmoxtf/test/test_utils.go
Labels: size/S

#367 fix(vm): Make `vm_id` computed
  docs/resources/virtual_environment_container.md
  example/resource_virtual_environment_container.tf
  example/resource_virtual_environment_vm.tf
  proxmoxtf/resource/vm.go
Labels: size/M

#378 feat(vm): add support for meta-data in cloud-init
  docs/resources/virtual_environment_vm.md
  example/resource_virtual_environment_file.tf
  example/resource_virtual_environment_vm.tf
  proxmox/nodes/tasks/tasks.go
  proxmoxtf/resource/vm.go
Labels: autoapprove, size/M

#379 fix(file): add check for supported content types when uploading file to a storage
  proxmoxtf/resource/file.go
Labels: autoapprove, size/S

#387 fix(lxc): add support for 'nixos'
  CONTRIBUTING.md
  proxmoxtf/resource/container.go
Labels: size/XS
