Repository bpg/terraform-provider-proxmox, pull requests merged in 2023-11, with the labels that each got.

#681 fix(vm): update validation and docs for `machine` attribute
  README.md
  docs/resources/virtual_environment_vm.md
  example/resource_virtual_environment_certificate.tf
  proxmoxtf/resource/validator/vm.go
  proxmoxtf/resource/validator/vm_test.go
  proxmoxtf/resource/vm.go
Labels: autoapprove, size/L

#686 fix(provider): sanitize PVE endpoint value
  docs/index.md
  proxmox/api/client.go
Labels: autoapprove, size/XS

#688 fix(storage): unmarshal error when list storage containing large files
  proxmox/nodes/storage_types.go
Labels: autoapprove, size/XS

#697 chore(docs): update VM ip address to mention the CIDR suffic requirement
  docs/resources/virtual_environment_vm.md
Labels: size/S

#704 fix(provider): do not blindly use first IP for SSH
  fwprovider/provider.go
  proxmoxtf/provider/provider.go
Labels: size/M

#690 fix(docs): add SSH info box to ressources needing it
  docs/resources/virtual_environment_file.md
  docs/resources/virtual_environment_vm.md
Labels: size/M

#699 chore(build): add devcontainer
  .devcontainer/devcontainer.json
  .vscode/settings.json
Labels: size/M

#703 fix(file): display warning if directory is not found
  proxmoxtf/resource/file.go
Labels: size/XS

#710 chore(docs): update hostpci id to mentions requirement around root user
  docs/resources/virtual_environment_vm.md
Labels: size/XS

#694 fix(provider): maxint for storage and vms
  proxmox/cluster/cluster_types.go
  proxmox/nodes/vms/vms_types.go
  proxmox/types/disk_size.go
  proxmox/types/disk_size_test.go
  proxmoxtf/resource/vm.go
Labels: size/M

#715 fix(vm): memory size datatype conversion causing `null` on read
  proxmoxtf/resource/vm.go
Labels: autoapprove, size/XS

#720 feat(vm): Add Win 11 as os type
  docs/resources/virtual_environment_vm.md
  proxmoxtf/resource/vm.go
Labels: size/XS

#724 feat(file): rename content type `backup` -> `dump` for backups
  docs/resources/virtual_environment_file.md
  proxmoxtf/resource/validator/vm.go
Labels: size/XS, automerge

#728 fix(vm): type error when unmarshalling `GetResponseData.data.memory`
  fwprovider/resource_options.go
  proxmox/cluster/options_types.go
  proxmox/nodes/vms/vms_types.go
  proxmox/types/common_types.go
Labels: autoapprove, size/M

#747 fix(docs): improve documentation for container feature flags
  docs/index.md
  docs/resources/virtual_environment_container.md
Labels: autoapprove, size/XS

#748 feat(provider): modify the proxmox api client to support connecting through an https proxy
  proxmox/api/client.go
Labels: size/XS

#750 fix(vm,lxc): file ID validator to allow `.` in a storage name
  proxmoxtf/resource/validator/file.go
  proxmoxtf/resource/validator/file_test.go
Labels: autoapprove, size/M

#753 fix(vm): resize image once imported
  proxmoxtf/resource/vm.go
Labels: size/XS

#755 fix(cluster): can't read back cluster options on PVE 8.1
  .gitignore
  .vscode/extensions.json
  .vscode/launch.json
  .vscode/settings.json
  fwprovider/resource_options.go
Labels: autoapprove, size/S

#756 fix(vm): unable to clone as non-root due to `hook_script`
  .vscode/settings.json
  proxmoxtf/resource/vm.go
Labels: autoapprove, size/S

#757 doc: add Elias Alvord as a sponsor
  README.md
Labels: autoapprove, size/XS
