Repository bpg/terraform-provider-proxmox, pull requests merged in 2023-12, with the labels that each got.

#762 fix(lxc): description is always showed as changed
  proxmoxtf/resource/container.go
Labels: autoapprove, size/XS

#743 feat(vm): Add support for setting the VM TPM State device
  docs/resources/virtual_environment_vm.md
  example/resource_virtual_environment_vm.tf
  proxmox/nodes/vms/vms_types.go
  proxmoxtf/resource/vm.go
Labels: size/L

#698 fix(docs): add more details about local testing of the provider
  CONTRIBUTING.md
  Makefile
  README.md
Labels: :hourglass: pending author's response, size/L

#766 fix(ci): fix release-please config after version bump
  release-please-config.json
Labels: autoapprove, size/XS

#767 fix(ci): fix release-please config after version bump (part2)
  .github/workflows/release-please.yml
  .release-please-manifest.json
  release-please-config.json
Labels: autoapprove, size/S

#768 chore(deps): revert bump google-github-actions/release-please-action from 3.7.13 to 4.0.0
  .github/workflows/release-please.yml
  .release-please-manifest.json
  release-please-config.json
Labels: autoapprove, size/M

#770 ci: configure release-please to bump minor version on breaking changes
  .github/workflows/release-please.yml
Labels: autoapprove, size/XS

#771 fix(docs): update CONTRIBUTING.md and other project docs
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .markdownlint.json
  CONTRIBUTING.md
Labels: autoapprove, size/M

#774 chore: configure vscode's linter to use proper .golangci.yml file
  .golangci.yml
  .vscode/settings.json
Labels: autoapprove

#777 chore(docs): update PR and issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/metrics.yml
  README.md
Labels: autoapprove, size/M

#783 feat(vm): support stopping (rather than shutting down) VMs on resource destroy
  docs/resources/virtual_environment_vm.md
  proxmoxtf/resource/vm.go
Labels: size/M

#785 fix(provider): typo in provider example
  examples/provider/provider.tf
Labels: size/XS, automerge

#797 fix(docs): add clone/full parameter for vms
  docs/resources/virtual_environment_vm.md
Labels: size/XS

#814 feat(vm): add `cpu.limit` attribute
  docs/resources/virtual_environment_vm.md
  example/resource_virtual_environment_vm.tf
  proxmoxtf/resource/vm.go
Labels: autoapprove, size/M

#811 fix(vm): panic at read when cloud-init drive is on directory storage
  proxmox/nodes/vms/vms_types.go
  proxmox/nodes/vms/vms_types_test.go
  proxmoxtf/resource/vm.go
Labels: autoapprove, size/L

#578 fix(vm): hostpci devices not showing up in refresh plan
  proxmox/nodes/vms/vms_types_test.go
  proxmoxtf/resource/vm.go
Labels: size/S

#822 feat(vm): add support up to 32 network interfaces
  proxmox/nodes/vms/vms_types.go
  proxmoxtf/resource/vm.go
Labels: size/L

#824 fix(provider): allow FQDN for `ssh.node.address` in provider's config
  docs/index.md
  proxmoxtf/provider/schema.go
Labels: size/XS

#827 fix(vm): update `smbios` during clone
  example/resource_virtual_environment_vm.tf
  proxmoxtf/resource/vm.go
Labels: autoapprove, size/XS

#829 docs: improve make example docs and add proxmox setup how-to
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  howtos/README.md
  howtos/setup-proxmox-for-make-example/README.md
Labels: size/M

#832 feat(vm, lxc): add new `initialization.dns.servers` param to vm and container
  docs/resources/virtual_environment_container.md
  docs/resources/virtual_environment_vm.md
  example/resource_virtual_environment_container.tf
  example/resource_virtual_environment_vm.tf
  proxmoxtf/resource/container.go
  proxmoxtf/resource/container_test.go
  proxmoxtf/resource/vm.go
  proxmoxtf/resource/vm_test.go
Labels: size/L

#834 chore(tests): Update acceptance tests to PVE 8.1, add docs
  .vscode/extensions.json
  .vscode/launch.json
  CONTRIBUTING.md
  Makefile
  fwprovider/tests/datasource_version_test.go
  fwprovider/tests/resource_container_test.go
  fwprovider/tests/resource_file_test.go
  fwprovider/tests/resource_linux_vlan_test.go
  howtos/README.md
  howtos/setup-proxmox-for-tests/README.md
  proxmox/ssh/client.go
Labels: autoapprove, size/M

#838 fix(lxc): add missing `onboot` param on container clone create
  example/resource_virtual_environment_container.tf
  proxmoxtf/resource/container.go
Labels: size/XS

#842 fix(vm,lxc): accept IPv6 in `initialization.dns.servers` attribute
  proxmoxtf/resource/container.go
  proxmoxtf/resource/vm.go
Labels: size/XS

#844 fix(vm,lxc): unexpected state drift when using `initialization.dns.servers`
  proxmoxtf/resource/container.go
  proxmoxtf/resource/vm.go
Labels: autoapprove, size/M

#840 fix(vm): Fixed missing default for disk discard
  proxmoxtf/resource/vm.go
Labels: size/XS

#848 feat(provider): add DNS lookup fallback for node IP resolution
  .markdownlintignore
  .vscode/settings.json
  fwprovider/provider.go
  proxmoxtf/provider/provider.go
Labels: autoapprove, size/M
