Repository bpg/terraform-provider-proxmox, pull requests merged in 2023-08, with the labels that each got.

#450 fix(vm): give `cache` the correct default value
  proxmoxtf/resource/vm.go
Labels: size/XS

#455 chore: add all-contributors to README.md
  .all-contributorsrc
  README.md
Labels: autoapprove, size/S

#459 chore(doc): add existing contributors
  .all-contributorsrc
  README.md
Labels: autoapprove, size/L

#461 chore(doc): cleanup readme
  .all-contributorsrc
  README.md
Labels: autoapprove, size/S

#463 fix(user): make `password` attribute optional
  docs/resources/virtual_environment_user.md
  proxmoxtf/resource/user.go
  proxmoxtf/resource/user_test.go
Labels: autoapprove, size/XS

#464 fix(API): remove HTTP client timeout
  proxmox/api/client.go
Labels: autoapprove, size/XS

#454 feat(vm): add support for SMBIOS settings
  docs/resources/virtual_environment_vm.md
  example/resource_virtual_environment_vm.tf
  proxmox/nodes/vms/vms_types.go
  proxmoxtf/resource/vm.go
Labels: autoapprove, size/L

#471 feat(file): ensure upload of ISO/VSTMPL is completed upon resource creation
  Makefile
  docs/resources/virtual_environment_file.md
  proxmox/nodes/storage.go
  proxmoxtf/resource/file.go
  proxmoxtf/resource/file_test.go
Labels: size/M

#474 fix(user): make `password` attribute optional
  example/resource_virtual_environment_user.tf
  proxmox/access/users_types.go
Labels: size/XS

#478 fix(vm): default disk cache is not set to `none` if not specified for an existing disk
  Makefile
  proxmoxtf/resource/file.go
  proxmoxtf/resource/vm.go
Labels: autoapprove

#479 fix(vm): ensure startup / shutdown delay is applied when order is not configured
  proxmoxtf/resource/vm.go
Labels: autoapprove, size/S

#486 feat(vm): support for non-default CloudInit interface and CloudInit storage change
  docs/resources/virtual_environment_vm.md
  example/resource_virtual_environment_vm.tf
  proxmoxtf/resource/vm.go
  proxmoxtf/resource/vm_test.go
Labels: size/L

#493 fix(vm): no IP address detection when VM contains bridges
  proxmox/nodes/vms/vms.go
Labels: size/XS

#496 fix(vm): fix index out of range when unmarshalling custompcidevice
  proxmox/nodes/vms/vms_types.go
  proxmox/nodes/vms/vms_types_test.go
Labels: size/M

#506 chore(vm): fix linter errors
  proxmoxtf/resource/vm.go
Labels: size/M

#505 feat(vm): pool update support
  proxmox/pools/pool_types.go
  proxmoxtf/resource/vm.go
Labels: size/M

#501 feat(vm): support for migration when the node name is modified
  docs/resources/virtual_environment_vm.md
  example/resource_virtual_environment_vm.tf
  proxmox/nodes/vms/vms_types.go
  proxmoxtf/resource/vm.go
Labels: size/M

#498 feat(ha): add support for Proxmox High Availability objects
  docs/data-sources/virtual_environment_hagroup.md
  docs/data-sources/virtual_environment_hagroups.md
  docs/data-sources/virtual_environment_haresource.md
  docs/data-sources/virtual_environment_haresources.md
  docs/resources/virtual_environment_hagroup.md
  docs/resources/virtual_environment_haresource.md
  examples/data-sources/proxmox_virtual_environment_hagroup/data-source.tf
  examples/data-sources/proxmox_virtual_environment_hagroups/data-source.tf
  examples/data-sources/proxmox_virtual_environment_haresource/data-source.tf
  examples/data-sources/proxmox_virtual_environment_haresources/data-source.tf
  examples/resources/proxmox_virtual_environment_hagroup/import.sh
  examples/resources/proxmox_virtual_environment_hagroup/resource.tf
  examples/resources/proxmox_virtual_environment_haresource/import.sh
  examples/resources/proxmox_virtual_environment_haresource/resource.tf
  internal/cluster/datasource_hagroup.go
  internal/cluster/datasource_hagroups.go
  internal/cluster/datasource_haresource.go
  internal/cluster/datasource_haresources.go
  internal/cluster/hagroup.go
  internal/cluster/haresource_model.go
  internal/cluster/resource_hagroup.go
  internal/cluster/resource_haresource.go
  internal/provider/provider.go
  internal/structure/attribute.go
  internal/types/common_types.go
  internal/types/ha_resource_id.go
  internal/types/ha_resource_id_test.go
  internal/types/ha_resource_state.go
  internal/types/ha_resource_state_test.go
  internal/types/ha_resource_type.go
  internal/types/ha_resource_type_test.go
  internal/validators/parse_validator.go
  proxmox/client.go
  proxmox/cluster/client.go
  proxmox/cluster/ha/client.go
  proxmox/cluster/ha/groups/client.go
  proxmox/cluster/ha/groups/hagroups.go
  proxmox/cluster/ha/groups/hagroups_types.go
  proxmox/cluster/ha/resources/client.go
  proxmox/cluster/ha/resources/resources.go
  proxmox/cluster/ha/resources/resources_types.go
  tools/tools.go
Labels: size/XXL

#500 feat(vm): support PCI device resource mapping
  docs/resources/virtual_environment_vm.md
  example/resource_virtual_environment_vm.tf
  proxmox/nodes/vms/vms_types.go
  proxmox/nodes/vms/vms_types_test.go
  proxmoxtf/resource/vm.go
Labels: size/M

#504 feat(vm): fix adding/removing hostpci devices forcing vm recreation
  proxmox/nodes/vms/vms_types.go
  proxmoxtf/resource/vm.go
Labels: size/S

#509 fix(vm): fix CloudInit datastore change support
  proxmoxtf/resource/vm.go
Labels: size/S

#508 fix(vm): fixed startup / shutdown behaviour on HA clusters
  proxmoxtf/resource/vm.go
Labels: size/M

#518 fix(provider): User-settable VLAN ID and name
  docs/resources/virtual_environment_network_linux_vlan.md
  examples/resources/proxmox_virtual_environment_network_linux_vlan/resource.tf
  internal/network/resource_linux_vlan.go
  proxmox/nodes/network_types.go
Labels: size/M

#526 fix(core): improve error handling while waiting for PVE tasks to complete
  proxmox/api/client.go
  proxmox/api/errors.go
  proxmox/nodes/storage.go
  proxmox/nodes/tasks/tasks.go
Labels: autoapprove, size/M

#528 fix(file): forced replacement of file resources that missing `timeout_upload` attribute
  proxmoxtf/resource/file.go
Labels: autoapprove, size/XS

#529 fix(node): creating linux_bridge with 'vlan_aware=false' or 'autostart=false'
  internal/network/resource_linux_bridge.go
  internal/test/network/resource_linux_bridge_test.go
Labels: autoapprove, size/M
