Repository bpg/terraform-provider-proxmox, pull requests merged in 2023-01, with the labels that each got.

#197 feat(vm): Add cloud-init network-config support
  docs/resources/virtual_environment_vm.md
  proxmox/virtual_environment_vm_types.go
  proxmoxtf/resource_virtual_environment_vm.go
Labels: go, size: s

#199 fix(vm): Make so that on_boot can be changed with update
  main.go
  proxmox/virtual_environment_client.go
  proxmox/virtual_environment_nodes.go
  proxmox/virtual_environment_vm_types_test.go
  proxmoxtf/data_source_virtual_environment_cluster_alias.go
  proxmoxtf/data_source_virtual_environment_cluster_aliases.go
  proxmoxtf/data_source_virtual_environment_datastores.go
  proxmoxtf/data_source_virtual_environment_datastores_test.go
  proxmoxtf/data_source_virtual_environment_dns.go
  proxmoxtf/data_source_virtual_environment_dns_test.go
  proxmoxtf/data_source_virtual_environment_group.go
  proxmoxtf/data_source_virtual_environment_groups.go
  proxmoxtf/data_source_virtual_environment_groups_test.go
  proxmoxtf/data_source_virtual_environment_hosts.go
  proxmoxtf/data_source_virtual_environment_hosts_test.go
  proxmoxtf/data_source_virtual_environment_nodes.go
  proxmoxtf/data_source_virtual_environment_pool.go
  proxmoxtf/data_source_virtual_environment_pools.go
  proxmoxtf/data_source_virtual_environment_role.go
  proxmoxtf/data_source_virtual_environment_roles.go
  proxmoxtf/data_source_virtual_environment_roles_test.go
  proxmoxtf/data_source_virtual_environment_time.go
  proxmoxtf/data_source_virtual_environment_user.go
  proxmoxtf/data_source_virtual_environment_users.go
  proxmoxtf/data_source_virtual_environment_version.go
  proxmoxtf/provider.go
  proxmoxtf/resource_virtual_environment_certificate.go
  proxmoxtf/resource_virtual_environment_cluster_alias.go
  proxmoxtf/resource_virtual_environment_cluster_ipset.go
  proxmoxtf/resource_virtual_environment_dns.go
  proxmoxtf/resource_virtual_environment_file.go
  proxmoxtf/resource_virtual_environment_group.go
  proxmoxtf/resource_virtual_environment_hosts.go
  proxmoxtf/resource_virtual_environment_pool.go
  proxmoxtf/resource_virtual_environment_role.go
  proxmoxtf/resource_virtual_environment_time.go
  proxmoxtf/resource_virtual_environment_user.go
  proxmoxtf/resource_virtual_environment_vm.go
Labels: go, size: m

#205 feat(vm): add support for "args" flag for VM
  docs/resources/virtual_environment_vm.md
  proxmox/virtual_environment_vm_types.go
  proxmoxtf/resource_virtual_environment_vm.go
  proxmoxtf/resource_virtual_environment_vm_test.go
Labels: documentation, go, size: m

#207 feat(lxc): Add option to customize RootFS size at LXC creation
  docs/resources/virtual_environment_container.md
  example/resource_virtual_environment_container.tf
  proxmoxtf/resource_virtual_environment_container.go
Labels: documentation, go, size: m, autoapprove

#209 chore: fix linter config
  .github/workflows/golangci-lint.yml
Labels: size: xs, yaml, autoapprove

#208 fix(vm): Add parser for CustomEFIDisk
  proxmox/utils.go
  proxmox/utils_test.go
  proxmox/virtual_environment_vm_types.go
  proxmoxtf/resource_virtual_environment_container.go
  proxmoxtf/resource_virtual_environment_vm.go
  proxmoxtf/utils.go
Labels: go, size: m

#212 feat(lxc): Add support for container tags
  docs/resources/virtual_environment_container.md
  example/resource_virtual_environment_container.tf
  proxmoxtf/resource_virtual_environment_container.go
  proxmoxtf/resource_virtual_environment_container_test.go
Labels: documentation, go, size: m

#215 chore: set up code coverage
  .github/workflows/test.yml
  README.md
  docs/resources/virtual_environment_container.md
  docs/resources/virtual_environment_vm.md
Labels: yaml, size: m, autoapprove

#216 chore(deps): bump dependencies
  .github/workflows/release-please.yml
  README.md
  go.mod
  go.sum
Labels: size: m, markdown, autoapprove

#217 feat(core): Add known hosts callback check for ssh connections
  go.mod
  go.sum
  proxmox/utils.go
  proxmox/utils_test.go
  proxmox/virtual_environment_client.go
  proxmox/virtual_environment_nodes.go
  proxmoxtf/resource_virtual_environment_file.go
Labels: go, size: m, autoapprove

#221 chore(deps): bump gem dependencies in /docs
  docs/Gemfile.lock
Labels: documentation, autoapprove
