Repository bpg/terraform-provider-proxmox, pull requests merged in 2023-10, with the labels that each got.

#595 chore(ci): cleanup CI flows
  .github/workflows/codeql-analysis.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/publish.yml
  .github/workflows/release-please.yml
  .github/workflows/test.yml
Labels: autoapprove, size/L

#596 fix(api): set min TLS version 1.3, secure HTTP-only cookie
  .github/workflows/golangci-lint.yml
  .github/workflows/test.yml
  proxmox/api/client.go
  proxmox/api/ticket_auth.go
  proxmoxtf/resource/file.go
Labels: autoapprove, size/S

#597 misc: fix tls min version typo
  proxmoxtf/resource/file.go
Labels: autoapprove

#598 fet(vm): allow `scsi` and `sata` interfaces for CloudInit Drive
  docs/resources/virtual_environment_vm.md
  example/resource_virtual_environment_vm.tf
  proxmox/nodes/tasks/tasks.go
  proxmox/nodes/tasks/tasks_types.go
  proxmox/nodes/vms/vms.go
  proxmoxtf/resource/validator/vm.go
  proxmoxtf/resource/vm.go
Labels: autoapprove, size/L

#602 misc: add sponsorship note
  README.md
Labels: autoapprove, size/XS

#605 feat(lxc): add support for the `start_on_boot` option
  docs/resources/virtual_environment_container.md
  proxmoxtf/resource/container.go
  proxmoxtf/resource/container_test.go
Labels: size/S

#610 fix(lxc): create container when authenticated with API token
  proxmoxtf/resource/container.go
Labels: autoapprove, size/S

#614 feat(vm): add option to enable multiqueue in network devices
  docs/resources/virtual_environment_vm.md
  example/resource_virtual_environment_vm.tf
  proxmoxtf/resource/vm.go
Labels: autoapprove, size/S

#615 fix(lxc): cloned container does not start by default
  fwprovider/tests/resource_container_test.go
  fwprovider/tests/resource_linux_vlan_test.go
  fwprovider/tests/test_support.go
  proxmox/nodes/containers/containers.go
  proxmoxtf/resource/container.go
Labels: autoapprove, size/L

#606 feat(vm): add 'path_in_datastore' disk argument
  docs/resources/virtual_environment_vm.md
  example/resource_virtual_environment_vm.tf
  proxmox/nodes/vms/vms_types.go
  proxmoxtf/resource/vm.go
  proxmoxtf/resource/vm_test.go
Labels: size/L

#620 fix(provider): add informative error around ssh-agent
  proxmox/ssh/client.go
Labels: size/XS

#622 fix(lxc): unmarshal string/int vmid as int when read container status
  proxmox/nodes/containers/containers_types.go
Labels: size/S

#633 fix(vm): better check for disk ownership
  proxmox/nodes/vms/vms_types.go
Labels: size/S

#635 fix(vm): set FileVolume for disks with file_id
  proxmoxtf/resource/vm.go
Labels: size/S

#645 chore: fix linter error
  fwprovider/datasource_hagroup.go
  fwprovider/datasource_hagroups.go
  fwprovider/datasource_haresource.go
  fwprovider/datasource_haresources.go
  fwprovider/datasource_version.go
  fwprovider/resource_hagroup.go
  fwprovider/resource_haresource.go
  fwprovider/resource_linux_bridge.go
  fwprovider/resource_linux_vlan.go
  fwprovider/resource_options.go
  proxmoxtf/test/utils.go
  utils/io_test.go
Labels: autoapprove, size/M

#648 feat(vm): add configurable timeout for VM create operation
  docs/resources/virtual_environment_vm.md
  proxmoxtf/resource/vm.go
Labels: autoapprove, size/S

#649 fix(file): handle missing file on state refresh
  fwprovider/tests/resource_file_test.go
  proxmoxtf/resource/file.go
Labels: autoapprove, size/M

#627 fix(vm): better handle of ctrl+c when qemu is not responding
  proxmox/nodes/vms/vms.go
Labels: size/L

#659 fix(doc): update README.md and `file` resource documentation
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  docs/resources/virtual_environment_file.md
Labels: autoapprove, size/M

#660 fix(vm): MAC address validator should allow lowercase hex
  proxmoxtf/resource/validator/network.go
  proxmoxtf/resource/validator/network_test.go
Labels: autoapprove, size/M

#670 fix(docs): document qemu-guest-agent behavior
  docs/resources/virtual_environment_vm.md
Labels: size/M

#666 feat(vm): add support for USB devices passthrough
  docs/resources/virtual_environment_vm.md
  example/resource_virtual_environment_vm.tf
  proxmox/nodes/vms/vms_types.go
  proxmox/nodes/vms/vms_types_test.go
  proxmoxtf/resource/vm.go
  proxmoxtf/resource/vm_test.go
Labels: size/L
