Repository bpg/terraform-provider-proxmox, pull requests merged in 2023-07, with the labels that each got.

#384 feat(vm): efi disk, cpu numa
  docs/resources/virtual_environment_vm.md
  example/resource_virtual_environment_vm.tf
  proxmox/nodes/vms/vms_types.go
  proxmox/types/disk_size.go
  proxmox/types/disk_size_test.go
  proxmoxtf/resource/utils.go
  proxmoxtf/resource/vm.go
  proxmoxtf/resource/vm_test.go
Labels: size/XL

#395 fix(file): spurious unsupported content type warning
  proxmoxtf/resource/file.go
Labels: autoapprove, size/XS

#386 fix(provider): Better handling of root@pam token
  proxmox/api/authenticator.go
  proxmox/api/client.go
  proxmox/api/ticket_auth.go
  proxmox/api/token_auth.go
  proxmoxtf/resource/vm.go
Labels: size/S

#393 fix: search for vm in cluster resources before calling node api
  proxmox/cluster/cluster.go
  proxmox/cluster/cluster_types.go
  proxmoxtf/resource/vm.go
Labels: size/M

#396 fix(docs): minor firewall options page improvement
  docs/resources/virtual_environment_firewall_options.md
Labels: size/XS

#397 fix(provider): fix config environment variables handling caused "rpc error"
  proxmoxtf/provider/provider.go
  proxmoxtf/provider/schema.go
Labels: autoapprove, size/L

#398 fix(vm): do not error on `read` at state refresh if VM is missing
  proxmox/cluster/cluster.go
  proxmoxtf/resource/vm.go
Labels: autoapprove, size/S

#409 chore(refactoring): remove accidentally added `types2` import alias
  internal/types/disk_size.go
  internal/types/disk_size_test.go
  internal/types/helpers.go
  proxmox/nodes/containers/containers.go
  proxmox/nodes/containers/containers_types.go
  proxmox/nodes/vms/vms_types.go
  proxmox/nodes/vms/vms_types_test.go
  proxmoxtf/resource/utils.go
  proxmoxtf/resource/vm.go
Labels: autoapprove

#390 feat: add import support for a lot of resources
  docs/resources/virtual_environment_cluster_firewall.md
  docs/resources/virtual_environment_cluster_firewall_security_group.md
  docs/resources/virtual_environment_container.md
  docs/resources/virtual_environment_dns.md
  docs/resources/virtual_environment_file.md
  docs/resources/virtual_environment_group.md
  docs/resources/virtual_environment_hosts.md
  docs/resources/virtual_environment_pool.md
  docs/resources/virtual_environment_role.md
  docs/resources/virtual_environment_time.md
  docs/resources/virtual_environment_user.md
  docs/resources/virtual_environment_vm.md
  proxmoxtf/resource/cluster/firewall/firewall.go
  proxmoxtf/resource/cluster/firewall/security_group.go
  proxmoxtf/resource/container.go
  proxmoxtf/resource/dns.go
  proxmoxtf/resource/file.go
  proxmoxtf/resource/file_test.go
  proxmoxtf/resource/group.go
  proxmoxtf/resource/hosts.go
  proxmoxtf/resource/pool.go
  proxmoxtf/resource/role.go
  proxmoxtf/resource/time.go
  proxmoxtf/resource/user.go
  proxmoxtf/resource/utils.go
  proxmoxtf/resource/utils_test.go
  proxmoxtf/resource/vm.go
Labels: size/L

#411 feat: add more valid cpu types
  docs/resources/virtual_environment_vm.md
  proxmoxtf/resource/utils.go
Labels: size/M

#412 fix(node): fix error when listing network interfaces of a node
  proxmox/nodes/network_types.go
Labels: autoapprove, size/XS

#414 fix(node): ignore field `bridge_fd` when listing network interfaces of a node
  proxmox/nodes/network_types.go
Labels: autoapprove, size/XS

#415 fix(firewall): ignore non-existent rules at read/delete
  proxmoxtf/resource/firewall/rules.go
Labels: autoapprove, size/S

#424 fix(firewall): add VM / container ID validation to firewall rules
  proxmoxtf/resource/container.go
  proxmoxtf/resource/firewall/selector.go
  proxmoxtf/resource/utils.go
  proxmoxtf/resource/validator/vm.go
  proxmoxtf/resource/vm.go
Labels: autoapprove, size/M

#428 fix(vm): add missing unmarshal for vm custom startup order
  proxmox/nodes/vms/vms_types.go
Labels: size/M

#429 fix(vm): add `interface` argument to `cdrom` block
  docs/resources/virtual_environment_vm.md
  example/resource_virtual_environment_network.tf
  proxmoxtf/resource/utils.go
  proxmoxtf/resource/vm.go
Labels: autoapprove, size/L

#430 fix(vm): do not reboot VM on config change if it is not running
  proxmoxtf/resource/vm.go
Labels: autoapprove, size/S

#394 feat(lxc): add support for lxc mount points
  docs/resources/virtual_environment_container.md
  example/resource_virtual_environment_container.tf
  proxmox/nodes/containers/client.go
  proxmox/nodes/containers/containers.go
  proxmox/nodes/containers/containers_types.go
  proxmoxtf/resource/container.go
  proxmoxtf/resource/container_test.go
  proxmoxtf/resource/utils.go
Labels: size/L

#436 fix(vm): fix for the api call upon empty disks
  proxmoxtf/resource/vm.go
Labels: size/XS

#435 fix(vm): Don't add an extra efi_disk entry
  proxmoxtf/resource/vm.go
Labels: size/XS

#438 chore: cleanup resource validators & utility code
  Makefile
  proxmoxtf/datasource/firewall/alias_test.go
  proxmoxtf/datasource/firewall/aliases_test.go
  proxmoxtf/datasource/firewall/ipset_test.go
  proxmoxtf/datasource/firewall/ipsets_test.go
  proxmoxtf/datasource/firewall/rule_test.go
  proxmoxtf/datasource/firewall/security_group_test.go
  proxmoxtf/datasource/firewall/security_groups_test.go
  proxmoxtf/resource/cluster/firewall/security_group_test.go
  proxmoxtf/resource/container.go
  proxmoxtf/resource/file.go
  proxmoxtf/resource/firewall/alias_test.go
  proxmoxtf/resource/firewall/ipset_test.go
  proxmoxtf/resource/firewall/options_test.go
  proxmoxtf/resource/firewall/rules_test.go
  proxmoxtf/resource/utils.go
  proxmoxtf/resource/validator/file.go
  proxmoxtf/resource/validator/network.go
  proxmoxtf/resource/validator/vm.go
  proxmoxtf/resource/validator/vm_test.go
  proxmoxtf/resource/vm.go
  proxmoxtf/resource/vm_test.go
  proxmoxtf/structure/schema.go
  proxmoxtf/structure/test.go
  proxmoxtf/structure/tools.go
  proxmoxtf/test/utils.go
Labels: autoapprove, size/XXL

#442 chore(docs): Update README.md
  README.md
  docs/Gemfile.lock
Labels: autoapprove, size/M

#440 feat(core): migrate `version` datasource to TF plugin framework
  .gitignore
  Makefile
  docs/data-sources/virtual_environment_version.md
  docs/resources/virtual_environment_network_linux_bridge.md
  docs/resources/virtual_environment_network_linux_vlan.md
  example/data_source_virtual_environment_version.tf
  examples/README.md
  examples/data-sources/proxmox_virtual_environment_version/data-source.tf
  examples/provider/provider.tf
  examples/provider/variables.tf
  examples/resources/proxmox_virtual_environment_network_linux_bridge/import.sh
  examples/resources/proxmox_virtual_environment_network_linux_bridge/resource.tf
  examples/resources/proxmox_virtual_environment_network_linux_vlan/import.sh
  examples/resources/proxmox_virtual_environment_network_linux_vlan/resource.tf
  internal/network/resource_linux_bridge.go
  internal/network/resource_linux_vlan.go
  internal/provider/datasource_version.go
  internal/provider/provider.go
  internal/test/datasource_version_test.go
  internal/test/network/resource_linux_bridge_test.go
  internal/test/network/resource_linux_vlan_test.go
  internal/test/provider_test.go
  internal/test/test_support.go
  main.go
  proxmox/version/version_types.go
  proxmoxtf/datasource/version.go
  proxmoxtf/datasource/version_test.go
  proxmoxtf/provider/datasources.go
  templates/data-sources.md.tmpl
  templates/resources.md.tmpl
  tools/tools.go
Labels: autoapprove, size/XL

#443 feat(vm): add support for disk `cache` option
  docs/resources/virtual_environment_vm.md
  example/resource_virtual_environment_vm.tf
  proxmox/nodes/vms/vms_types.go
  proxmox/nodes/vms/vms_types_test.go
  proxmoxtf/resource/vm.go
Labels: autoapprove, size/M

#445 feat(vm): add support for start/shutdown order configuration
  docs/resources/virtual_environment_vm.md
  example/resource_virtual_environment_vm.tf
  proxmoxtf/resource/vm.go
Labels: autoapprove, size/L

#446 chore: update dependencies, cleanup docs
  .github/ISSUE_TEMPLATE/bug_report.md
  .github_changelog_generator
  .gitignore
  .go-version
  Makefile
  README.md
  docs/resources/virtual_environment_network_linux_bridge.md
  docs/resources/virtual_environment_network_linux_vlan.md
  examples/README.md
  go.mod
  go.sum
  tools/tools.go
Labels: autoapprove, size/L

#447 fix(vm): cloned VM with `efi_disk` got re-created at re-apply
  proxmoxtf/resource/vm.go
Labels: autoapprove, size/S
