Repository bpg/terraform-provider-proxmox, pull requests merged in 2023-04, with the labels that each got.

#282 feat(vm): Add scsi_hardware field
  proxmoxtf/resource_virtual_environment_vm.go
  proxmoxtf/resource_virtual_environment_vm_test.go
  proxmoxtf/utils.go
Labels: size/M

#283 chore: add missing docs
  .github/PULL_REQUEST_TEMPLATE.md
  docs/resources/virtual_environment_vm.md
Labels: autoapprove, size/S

#288 fix(provider): Deprecate `virtual_environment` block
  docs/index.md
  example/main.tf
  proxmoxtf/provider/provider.go
  proxmoxtf/provider/provider_test.go
  proxmoxtf/provider/schema.go
Labels: documentation, go, size/L

#290 chore: cleanup and fix linter errors
  .github/auto-label.yaml
  example/resource_virtual_environment_vm.tf
  proxmoxtf/config.go
  proxmoxtf/resource/firewall/rules.go
  proxmoxtf/resource/validator/firewall.go
Labels: autoapprove, size/M

#219 feat(vm): add support for `boot_order` argument for VM
  docs/resources/virtual_environment_vm.md
  proxmox/virtual_environment_vm_types.go
  proxmoxtf/resource/vm.go
  proxmoxtf/resource/vm_test.go
Labels: documentation, go, size/L

#291 fix(file): "Permission denied" error when creating a file by a non-root user
  proxmox/datastores.go
  proxmox/datastores_types.go
  proxmox/virtual_environment_datastores.go
  proxmoxtf/resource/file.go
Labels: autoapprove, size/XL

#293 fix(core): Error when open SSH session on Windows
  .github/PULL_REQUEST_TEMPLATE.md
  proxmox/virtual_environment_nodes.go
Labels: autoapprove, size/XS

#295 fix(firewall): Add support for `firewall` flag for LXC/VM net adapters
  docs/resources/virtual_environment_container.md
  docs/resources/virtual_environment_vm.md
  proxmoxtf/resource/container.go
  proxmoxtf/resource/vm.go
Labels: autoapprove, size/M

#305 feat(vm): Wait for the VM creation task to complete
  proxmox/virtual_environment_vm.go
  proxmox/virtual_environment_vm_types.go
  proxmoxtf/resource/vm.go
Labels: autoapprove, size/M

#308 fix(file): SSH file upload on Windows
  .github/ISSUE_TEMPLATE/bug_report.md
  proxmox/datastores.go
  proxmox/datastores_types.go
  proxmox/virtual_environment_nodes.go
  proxmoxtf/resource/file.go
Labels: autoapprove, size/M

#312 fix(firewall): use correct default value for firewall
  proxmoxtf/resource/vm.go
Labels: size/XS
