Repository bpg/terraform-provider-proxmox, pull requests merged in 2024-03, with the labels that each got.

#1076 feat(provider): add support for private key authentication for SSH
  .github/workflows/test.yml
  docs/index.md
  fwprovider/provider.go
  fwprovider/tests/resource_container_test.go
  fwprovider/tests/resource_file_test.go
  proxmox/ssh/client.go
  proxmoxtf/provider/provider.go
  proxmoxtf/provider/schema.go
Labels: autoapprove, size/L

#1085 feat(file)!: snippets upload using SSH input stream
  .github/workflows/test.yml
  .github/workflows/testacc.yml
  docs/index.md
  example/main.tf
  example/variables.tf
  fwprovider/tests/resource_file_test.go
  proxmox/ssh/client.go
  proxmoxtf/resource/file.go
Labels: autoapprove, size/L

#1086 feat(vm): add `VLAN` trunk support
  docs/resources/virtual_environment_vm.md
  example/resource_virtual_environment_trunks.tf
  fwprovider/tests/resource_vm_test.go
  proxmoxtf/resource/vm/vm.go
Labels: size/L

#1088 fix(docs): fix wrong startup delay attributes
  docs/resources/virtual_environment_container.md
  docs/resources/virtual_environment_vm.md
Labels: size/S

#1091 chore(docs): minor improvements around SSH private key usage
  docs/index.md
Labels: autoapprove, size/S

#1092 fix(ci): TestAccResourceVMNetwork acc test fails when run on CI
  fwprovider/tests/resource_vm_test.go
Labels: autoapprove, size/S

#1101 fix: allow LDAP realm API tokens
  fwprovider/provider.go
  proxmoxtf/provider/schema.go
Labels: size/XS

#1095 fix(network): multiple fixes to `network_linux_bridge` resource
  fwprovider/resource_linux_bridge.go
  fwprovider/tests/resource_download_file_test.go
  fwprovider/tests/resource_linux_bridge_test.go
  fwprovider/tests/resource_user_test.go
  fwprovider/tests/resource_vm_test.go
  fwprovider/tests/test_support.go
Labels: autoapprove, size/L

#1108 chore: minor cleanups and doc updates
  .github/workflows/test.yml
  .vscode/settings.json
  docs/index.md
  proxmox/ssh/client.go
  proxmoxtf/resource/file.go
  proxmoxtf/resource/vm/vm.go
Labels: autoapprove, size/M

#1103 fix(vm): timeout when resizing a disk during clone
  proxmox/nodes/vms/vms.go
Labels: size/S

#1113 fix(provider): EOF error when closing SSH session
  main.go
  proxmox/ssh/client.go
Labels: autoapprove, size/M

#1118 fix(ci): missing releases from HashiCorp Registry
  .github/workflows/publish.yml
  .goreleaser.yml
  terraform-registry-manifest.json
Labels: autoapprove, size/M

#1124 feat(vm): add support for disk `aio`, `backup`, `iops*` attributes
  .vscode/settings.json
  docs/resources/virtual_environment_vm.md
  fwprovider/tests/resource_vm_test.go
  proxmox/nodes/vms/customstoragedevice.go
  proxmox/nodes/vms/vms_types.go
  proxmoxtf/resource/vm/disk/disk.go
  proxmoxtf/resource/vm/disk/schema.go
  proxmoxtf/resource/vm/vm.go
Labels: autoapprove, size/XL

#1126 feat(vm): add support for `protection` attribute
  docs/resources/virtual_environment_vm.md
  fwprovider/tests/resource_vm_test.go
  proxmox/nodes/vms/vms_types.go
  proxmoxtf/resource/vm/vm.go
Labels: autoapprove, size/M

#1127 chore(vm): refactoring: extract network device code from vm.go
  proxmoxtf/datasource/datastores_test.go
  proxmoxtf/datasource/dns_test.go
  proxmoxtf/datasource/firewall/alias_test.go
  proxmoxtf/datasource/firewall/aliases_test.go
  proxmoxtf/datasource/firewall/ipset_test.go
  proxmoxtf/datasource/firewall/ipsets_test.go
  proxmoxtf/datasource/firewall/rule_test.go
  proxmoxtf/datasource/firewall/security_group_test.go
  proxmoxtf/datasource/firewall/security_groups_test.go
  proxmoxtf/datasource/group_test.go
  proxmoxtf/datasource/groups_test.go
  proxmoxtf/datasource/hosts_test.go
  proxmoxtf/datasource/nodes_test.go
  proxmoxtf/datasource/pool_test.go
  proxmoxtf/datasource/pools_test.go
  proxmoxtf/datasource/role_test.go
  proxmoxtf/datasource/roles_test.go
  proxmoxtf/datasource/time_test.go
  proxmoxtf/datasource/user_test.go
  proxmoxtf/datasource/users_test.go
  proxmoxtf/datasource/vm_test.go
  proxmoxtf/datasource/vms_test.go
  proxmoxtf/provider/provider_test.go
  proxmoxtf/resource/certificate_test.go
  proxmoxtf/resource/cluster/firewall/security_group_test.go
  proxmoxtf/resource/container/container_test.go
  proxmoxtf/resource/dns_test.go
  proxmoxtf/resource/file_test.go
  proxmoxtf/resource/firewall/alias_test.go
  proxmoxtf/resource/firewall/ipset_test.go
  proxmoxtf/resource/firewall/options_test.go
  proxmoxtf/resource/firewall/rules_test.go
  proxmoxtf/resource/group_test.go
  proxmoxtf/resource/hosts_test.go
  proxmoxtf/resource/pool_test.go
  proxmoxtf/resource/role_test.go
  proxmoxtf/resource/time_test.go
  proxmoxtf/resource/user_test.go
  proxmoxtf/resource/vm/disk/schema_test.go
  proxmoxtf/resource/vm/network/network.go
  proxmoxtf/resource/vm/network/schema.go
  proxmoxtf/resource/vm/network/schema_test.go
  proxmoxtf/resource/vm/validators.go
  proxmoxtf/resource/vm/vm.go
  proxmoxtf/resource/vm/vm_test.go
  proxmoxtf/test/utils.go
Labels: autoapprove, size/XXL

#1129 feat(vm): add support for `disconnected` attribute in network interface
  docs/resources/virtual_environment_vm.md
  fwprovider/tests/resource_vm_test.go
  proxmox/nodes/vms/vms_types.go
  proxmoxtf/resource/vm/network/network.go
  proxmoxtf/resource/vm/network/schema.go
Labels: autoapprove, size/L

#1132 fix(doc): fix `sudo` configuration steps
  docs/index.md
Labels: autoapprove, size/XS

#1133 fix(docs): typo in `container.console` attribute `mode` -> `type`
  docs/resources/virtual_environment_container.md
Labels: size/XS

#1136 fix(examples): `datastore_id` is missing in `initialization` block for vm
  example/resource_virtual_environment_vm.tf
Labels: size/XS

#1140 feat(lxc): support hook script for LXC
  docs/resources/virtual_environment_container.md
  proxmoxtf/resource/container/container.go
  proxmoxtf/resource/container/container_test.go
Labels: size/M

#1146 feat(lxc): add configurable timeout for container creation
  docs/resources/virtual_environment_container.md
  proxmoxtf/resource/container/container.go
Labels: autoapprove, size/S

#1151 feat(vm): add proxmox_virtual_environment_node datasource
  docs/data-sources/virtual_environment_node.md
  example/data_source_virtual_environment_node.tf
  fwprovider/tests/datasource_node_test.go
  proxmox/nodes/nodes.go
  proxmox/nodes/nodes_types.go
  proxmoxtf/datasource/node.go
  proxmoxtf/provider/datasources.go
Labels: size/L

#1153 feat(vm): add support for cpu `affinity` attribute (#1148)
  docs/resources/virtual_environment_vm.md
  example/resource_virtual_environment_vm.tf
  proxmox/nodes/vms/vms_types.go
  proxmoxtf/resource/vm/validators.go
  proxmoxtf/resource/vm/vm.go
Labels: size/M

#1161 fix(lxc): improve configurable timeouts for containers operations
  docs/resources/virtual_environment_container.md
  proxmoxtf/resource/container/container.go
Labels: size/S

#1141 fix(vm): re-use ide, sata, and scsi cloud-init storage (#1083)
  fwprovider/tests/resource_vm_test.go
  proxmoxtf/resource/vm/vm.go
Labels: size/L

#1158 feat(vm): add support for memory `hugepages` and `keep_hugepages` attributes
  docs/resources/virtual_environment_vm.md
  example/resource_virtual_environment_vm.tf
  proxmox/nodes/vms/vms_types.go
  proxmoxtf/resource/vm/vm.go
Labels: size/L

#1168 fix: prevent authenticating multiple times in parallel
  proxmox/api/ticket_auth.go
Labels: size/XS
