Repository bpg/terraform-provider-proxmox, pull requests merged in 2024-05, with the labels that each got.

#1249 fix: use `raw` file format for `efi_disk` by default
  docs/resources/virtual_environment_vm.md
  fwprovider/tests/resource_vm_test.go
  proxmoxtf/resource/vm/vm.go
Labels: autoapprove, size/S

#1253 fix(vm): only set `initialization.upgrade` attribute when not using custom cloud-init file
  fwprovider/tests/resource_vm_test.go
  proxmoxtf/resource/vm/vm.go
Labels: size/XS

#1260 fix(vm): fix timeout when resizing custom disk at create
  proxmoxtf/resource/vm/disk/disk.go
  proxmoxtf/resource/vm/vm.go
Labels: autoapprove, size/L

#1269 fix(code): update acc tests to PVE 8.2
  fwprovider/tests/datasource_version_test.go
  fwprovider/tests/resource_vm_test.go
Labels: autoapprove, size/S

#1159 feat(access): add proxmox user token
  docs/resources/virtual_environment_user_token.md
  examples/resources/proxmox_virtual_environment_user_token/import.sh
  examples/resources/proxmox_virtual_environment_user_token/resource.tf
  fwprovider/access/resource_user_token.go
  fwprovider/provider.go
  fwprovider/tests/resource_user_test.go
  fwprovider/tests/test_environment.go
  proxmox/access/user_token.go
  proxmox/access/user_token_types.go
  tools/tools.go
Labels: size/XL

#1166 feat(access): add ACL resource
  Makefile
  docs/resources/virtual_environment_acl.md
  examples/resources/proxmox_virtual_environment_acl/import.sh
  examples/resources/proxmox_virtual_environment_acl/resource.tf
  fwprovider/access/resource_acl.go
  fwprovider/access/resource_acl_model.go
  fwprovider/access/resource_user_token.go
  fwprovider/provider.go
  fwprovider/structure/attribute.go
  fwprovider/tests/resource_acl_test.go
  fwprovider/tests/resource_download_file_test.go
  fwprovider/tests/resource_user_test.go
  fwprovider/types/tags/value.go
  fwprovider/vm/resource.go
  go.mod
  go.sum
  proxmox/access/acl.go
  proxmox/access/acl_types.go
  proxmox/helpers/ptr/ptr.go
  proxmox/nodes/vms/customstoragedevice.go
  proxmox/nodes/vms/vms_types_test.go
  proxmox/types/common_types.go
  proxmox/types/disk_size.go
  proxmox/types/helpers.go
  proxmoxtf/resource/vm/vm.go
  tools/tools.go
Labels: size/XL

#1270 feat(provider): add support for `ssh-agent` on Windows
  docs/index.md
  go.mod
  go.sum
  proxmox/ssh/client.go
  proxmox/ssh/client_notwindows.go
  proxmox/ssh/client_windows.go
Labels: size/M

#1282 fix(access): change acl internal ID from url path format to position-based format
  docs/resources/virtual_environment_acl.md
  examples/resources/proxmox_virtual_environment_acl/import.sh
  fwprovider/access/resource_acl.go
  fwprovider/access/resource_acl_model.go
  fwprovider/tests/resource_acl_test.go
Labels: autoapprove, size/M

#1286 misc(vm): fix CustomBool conversion bug introduced in `acl` implementation
  fwprovider/access/resource_acl_model.go
  fwprovider/access/resource_user_token.go
  fwprovider/vm/resource.go
  proxmox/nodes/vms/vms_types_test.go
  proxmox/types/common_types.go
Labels: autoapprove, size/M

#1287 fix(vm): `cdrom` is not attached when creating a VM from scratch
  fwprovider/tests/resource_vm_test.go
  proxmoxtf/resource/vm/vm.go
Labels: autoapprove, size/M

#1293 fix(access): user token `expiration_date` handling
  README.md
  fwprovider/access/resource_user_token.go
  fwprovider/tests/resource_user_test.go
Labels: autoapprove, size/M

#1295 feat(vm): remove support for `initialization.upgrade` attribute
  docs/resources/virtual_environment_vm.md
  fwprovider/tests/resource_vm_test.go
  proxmox/nodes/vms/vms_types.go
  proxmoxtf/resource/vm/vm.go
Labels: autoapprove, size/M

#1297 fix(vm): yet another fix for disk reordering
  fwprovider/tests/resource_vm_test.go
  proxmoxtf/resource/vm/disk/disk.go
  proxmoxtf/resource/vm/vm.go
  proxmoxtf/structure/schema.go
  utils/maps.go
  utils/maps_test.go
Labels: autoapprove, size/M

#1310 chore(vm2): add support for `cpu`
  docs/resources/virtual_environment_vm2.md
  fwprovider/resource_options.go
  fwprovider/tests/resource_time_test.go
  fwprovider/tests/resource_vm2_test.go
  fwprovider/types/stringset/attribute.go
  fwprovider/types/stringset/type.go
  fwprovider/types/stringset/value.go
  fwprovider/vm/cpu/resource_cpu.go
  fwprovider/vm/cpu/resource_cpu_model.go
  fwprovider/vm/cpu/resource_cpu_schema.go
  fwprovider/vm/resource_model.go
  fwprovider/vm/resource_vm.go
  fwprovider/vm/resource_vm_model.go
  fwprovider/vm/resource_vm_schema.go
  proxmox/nodes/vms/vms_types.go
  proxmox/types/common_types.go
  proxmoxtf/resource/vm/vm.go
  qodana.yaml
Labels: autoapprove, size/XXL

#1311 chore(vm2): cleanup `cpu` implementation, refactor rearrange acc tests
  .github/workflows/testacc.yml
  .golangci.yml
  Makefile
  docs/guides/cloud-init.md
  docs/resources/virtual_environment_file.md
  docs/resources/virtual_environment_vm2.md
  example/resource_virtual_environment_file.tf
  examples/guides/cloud-init/custom/cloud-config.tf
  fwprovider/access/resource_acl_test.go
  fwprovider/access/resource_user_test.go
  fwprovider/hardwaremapping/resource_hardware_mapping_test.go
  fwprovider/network/resource_linux_bridge_test.go
  fwprovider/network/resource_linux_vlan_test.go
  fwprovider/resource_download_file_test.go
  fwprovider/resource_options_test.go
  fwprovider/test/datasource_node_test.go
  fwprovider/test/datasource_version_test.go
  fwprovider/test/resource_container_test.go
  fwprovider/test/resource_file_test.go
  fwprovider/test/resource_firewall_test.go
  fwprovider/test/resource_time_test.go
  fwprovider/test/resource_vm_test.go
  fwprovider/test/test_environment.go
  fwprovider/test/test_support.go
  fwprovider/tests/resource_vm2_test.go
  fwprovider/vm/cpu/resource_cpu.go
  fwprovider/vm/cpu/resource_cpu_schema.go
  fwprovider/vm/cpu/resource_cpu_test.go
  fwprovider/vm/resource_vm.go
  fwprovider/vm/resource_vm_model.go
  fwprovider/vm/resource_vm_test.go
  templates/resources/virtual_environment_vm2.md.tmpl
Labels: autoapprove, size/XXL

#1315 fix(file): upload timeout with 596 response code
  proxmox/nodes/storage/content.go
Labels: autoapprove, size/S

#1317 fix(vm): allow `clone` to pass with warnings
  proxmox/nodes/tasks/tasks.go
  proxmox/nodes/vms/vms.go
Labels: autoapprove, size/M

#1318 chore(vm2): add datasource implementation
  docs/data-sources/virtual_environment_vm2.md
  docs/resources/virtual_environment_vm2.md
  fwprovider/provider.go
  fwprovider/vm/cpu/datasource_schema.go
  fwprovider/vm/cpu/resource.go
  fwprovider/vm/cpu/resource_model.go
  fwprovider/vm/cpu/resource_schema.go
  fwprovider/vm/cpu/resource_test.go
  fwprovider/vm/datasource.go
  fwprovider/vm/datasource_schema.go
  fwprovider/vm/resource.go
  fwprovider/vm/resource_schema.go
  fwprovider/vm/resource_test.go
  fwprovider/vm/resource_vm_model.go
  fwprovider/vm/vm_model.go
  templates/data-sources/virtual_environment_vm2.md.tmpl
  tools/tools.go
Labels: autoapprove, size/XL

#1326 feat(vm): add support for `vga.clipboard`, `virtio-gl` type
  docs/resources/virtual_environment_vm.md
  fwprovider/test/resource_vm_test.go
  proxmox/nodes/vms/vms_types.go
  proxmoxtf/resource/vm/validators.go
  proxmoxtf/resource/vm/vm.go
Labels: autoapprove, size/L

#1327 fix(lxc): `mount_point.backup` should be `false` by default
  docs/resources/virtual_environment_container.md
  proxmoxtf/resource/container/container.go
Labels: autoapprove, size/XS

#1329 docs(provider): document expectations for the default `root` shell on PVE nodes
  docs/index.md
Labels: autoapprove, size/XS

#1330 fix(vm): check task warning status against exit code
  proxmox/nodes/tasks/tasks.go
Labels: size/XS

#1338 fix(vm): host parameter is optional if using mapping for usb
  proxmox/nodes/vms/vms_types.go
  proxmoxtf/resource/vm/vm.go
Labels: size/S

#1340 fix(vm): regression: `vga.clipboard` attribute check
  example/resource_virtual_environment_vm.tf
  fwprovider/test/resource_vm_test.go
  fwprovider/vm/vga/resource_test.go
  proxmoxtf/resource/vm/vm.go
Labels: autoapprove, size/S

#1336 fix(vm): adding disks causes VM to be re-created
  .github/workflows/testacc.yml
  fwprovider/test/resource_container_test.go
  fwprovider/test/resource_vm_test.go
  fwprovider/test/test_environment.go
  proxmoxtf/resource/vm/disk/disk.go
  proxmoxtf/resource/vm/disk/schema.go
  proxmoxtf/resource/vm/vm.go
Labels: autoapprove, size/L
