Repository bpg/terraform-provider-proxmox, pull requests merged in 2024-01, with the labels that each got.

#837 feat(storage): add new resource `proxmox_virtual_environment_download_file`
  docs/resources/virtual_environment_container.md
  docs/resources/virtual_environment_download_file.md
  docs/resources/virtual_environment_file.md
  docs/resources/virtual_environment_vm.md
  example/resource_virtual_environment_container.tf
  example/resource_virtual_environment_download_file.tf
  example/resource_virtual_environment_vm.tf
  examples/resources/proxmox_virtual_environment_download_file/resource.tf
  fwprovider/provider.go
  fwprovider/resource_download_file.go
  fwprovider/tests/resource_download_file_test.go
  fwprovider/tests/resource_file_test.go
  fwprovider/tests/test_support.go
  proxmox/nodes/client.go
  proxmox/nodes/query_url_metadata.go
  proxmox/nodes/query_url_metadata_types.go
  proxmox/nodes/storage/client.go
  proxmox/nodes/storage/content.go
  proxmox/nodes/storage/content_types.go
  proxmox/nodes/storage/download_url.go
  proxmox/nodes/storage/download_url_types.go
  proxmox/nodes/storage/status.go
  proxmox/nodes/storage/status_types.go
  proxmox/nodes/storage/storage.go
  proxmox/nodes/storage/storage_types.go
  proxmox/nodes/storage/upload.go
  proxmox/nodes/storage/upload_types.go
  proxmox/nodes/tasks/client.go
  proxmox/nodes/tasks/tasks.go
  proxmoxtf/datasource/datastores.go
  proxmoxtf/resource/file.go
  proxmoxtf/resource/vm.go
  tools/tools.go
Labels: size/XXL

#846 chore(docs): update provider documentation with more details about token use
  CHANGELOG.md
  docs/index.md
Labels: autoapprove, size/L

#858 misc: Update README.md
  README.md
Labels: autoapprove, size/XS

#862 fix(vm): optimize retrieval of VM volume attributes from a datastore
  proxmox/nodes/storage/content.go
  proxmoxtf/resource/vm.go
Labels: size/S

#872 fix(doc): typos in `proxmox_virtual_environment_file` resource
  docs/resources/virtual_environment_file.md
Labels: autoapprove, size/XS

#874 fix(provider): check if err is nil
  proxmoxtf/provider/provider.go
Labels: size/XS

#877 fix(vm): missing disks when importing VM to a TF state
  proxmoxtf/resource/vm.go
Labels: autoapprove, size/XS

#882 fix(docs): fix indentation in `virtual_environment_container.md`
  docs/resources/virtual_environment_container.md
Labels: size/XS

#890 chore(ci): update
  .github/workflows/golangci-lint.yml
  .github/workflows/metrics.yml
  .github/workflows/publish.yml
  .github/workflows/release-please.yml
  .github/workflows/semgrep.yml
  .github/workflows/stale.yaml
  .github/workflows/test.yml
Labels: size/L

#891 chore(ci): switch to renovate
  .github/dependabot.yml
  .github/renovate.json5
Labels: autoapprove, size/M

#923 feat(lxc): add container startup options
  docs/resources/virtual_environment_container.md
  example/resource_virtual_environment_container.tf
  proxmoxtf/resource/container.go
Labels: size/L

#928 fix(vm): panic on empty `initialization.dns` block
  proxmoxtf/resource/vm.go
Labels: autoapprove, size/L

#929 chore(docs): remove static website generator with ruby dependencies
  docs/.gitignore
  docs/404.html
  docs/Gemfile
  docs/Gemfile.lock
  docs/_config.yml
  docs/assets/js/search-data.json
  docs/data-sources/index.html
  docs/data-sources/virtual_environment_datastores.md
  docs/data-sources/virtual_environment_dns.md
  docs/data-sources/virtual_environment_group.md
  docs/data-sources/virtual_environment_groups.md
  docs/data-sources/virtual_environment_hosts.md
  docs/data-sources/virtual_environment_nodes.md
  docs/data-sources/virtual_environment_pool.md
  docs/data-sources/virtual_environment_pools.md
  docs/data-sources/virtual_environment_role.md
  docs/data-sources/virtual_environment_roles.md
  docs/data-sources/virtual_environment_time.md
  docs/data-sources/virtual_environment_user.md
  docs/data-sources/virtual_environment_users.md
  docs/data-sources/virtual_environment_vm.md
  docs/data-sources/virtual_environment_vms.md
  docs/index.md
  docs/resources/index.html
  docs/resources/virtual_environment_certificate.md
  docs/resources/virtual_environment_cluster_firewall.md
  docs/resources/virtual_environment_cluster_firewall_security_group.md
  docs/resources/virtual_environment_container.md
  docs/resources/virtual_environment_dns.md
  docs/resources/virtual_environment_file.md
  docs/resources/virtual_environment_firewall_alias.md
  docs/resources/virtual_environment_firewall_ipset.md
  docs/resources/virtual_environment_firewall_options.md
  docs/resources/virtual_environment_firewall_rules.md
  docs/resources/virtual_environment_group.md
  docs/resources/virtual_environment_hosts.md
  docs/resources/virtual_environment_pool.md
  docs/resources/virtual_environment_role.md
  docs/resources/virtual_environment_time.md
  docs/resources/virtual_environment_user.md
  docs/resources/virtual_environment_vm.md
Labels: autoapprove, size/L

#931 feat: add min-tls option to provider config
  docs/index.md
  docs/resources/virtual_environment_file.md
  fwprovider/provider.go
  fwprovider/tests/test_support.go
  proxmox/api/client.go
  proxmoxtf/provider/provider.go
  proxmoxtf/provider/provider_test.go
  proxmoxtf/provider/schema.go
  proxmoxtf/resource/file.go
Labels: size/M

#943 chore(docs): update README.md, add note about OpenTofu support
  .vscode/settings.json
  Makefile
  README.md
Labels: autoapprove, size/M

#944 chore(ci): add link checker, reformat actions code
  .github/workflows/golangci-lint.yml
  .github/workflows/link-check.yml
  .github/workflows/metrics.yml
  .github/workflows/publish.yml
  .github/workflows/release-please.yml
  .github/workflows/semgrep.yml
  .github/workflows/stale.yaml
  .github/workflows/test.yml
Labels: autoapprove, size/L

#945 chore(docs): move list of contributors to CONTRIBUTORS.md
  .all-contributorsrc
  CONTRIBUTORS.md
  README.md
Labels: autoapprove, size/L

#950 feat(provider): use `sudo` to execute commands over SSH
  .markdownlint.json
  docs/index.md
  proxmox/ssh/client.go
  proxmoxtf/resource/vm.go
Labels: autoapprove, size/L

#951 chore(ci): update issue templates, renovate config
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/renovate.json5
Labels: autoapprove, size/XS

#961 fix(docs): Inconsistent indentations in docs
  docs/data-sources/virtual_environment_group.md
  docs/data-sources/virtual_environment_pool.md
  docs/data-sources/virtual_environment_user.md
  docs/data-sources/virtual_environment_vms.md
  docs/resources/virtual_environment_cluster_firewall.md
  docs/resources/virtual_environment_cluster_firewall_security_group.md
  docs/resources/virtual_environment_container.md
  docs/resources/virtual_environment_file.md
  docs/resources/virtual_environment_firewall_ipset.md
  docs/resources/virtual_environment_firewall_options.md
  docs/resources/virtual_environment_firewall_rules.md
  docs/resources/virtual_environment_group.md
  docs/resources/virtual_environment_hosts.md
  docs/resources/virtual_environment_pool.md
  docs/resources/virtual_environment_user.md
  docs/resources/virtual_environment_vm.md
Labels: size/XXL

#966 fix(vm): regression: `sudo: command not found` when creating a VM
  docs/index.md
  proxmox/ssh/client.go
  proxmoxtf/resource/vm.go
Labels: autoapprove, size/S

#970 feat(provider): add SOCKS5 proxy support for SSH connections
  docs/index.md
  fwprovider/provider.go
  fwprovider/tests/resource_file_test.go
  proxmox/ssh/client.go
  proxmoxtf/provider/provider.go
  proxmoxtf/provider/schema.go
Labels: autoapprove, size/L

#974 fix(pool): missing `pool_id` after import
  proxmoxtf/resource/pool.go
Labels: autoapprove, size/S

#976 fix(docs): fix broken links
  CONTRIBUTING.md
  README.md
Labels: autoapprove, size/XS

#977 fix(lxc): panic on empty `initialization.ip_config` block
  proxmoxtf/resource/container.go
Labels: autoapprove, size/XS

#978 fix(vm): `timeout_start_vm` is ignored
  proxmox/nodes/vms/vms.go
  proxmox/nodes/vms/vms_types.go
Labels: autoapprove, size/S

#980 fix(docs): fix documentation tree structure in the TF registry
  docs/guides/cloud-image.md
  docs/guides/cloud-init.md
  docs/guides/setup-proxmox-for-tests.md
  docs/index.md
  release-please-config.json
Labels: autoapprove, size/S
