Repository bpg/terraform-provider-proxmox, pull requests merged in 2024-06, with the labels that each got.

#1345 fix(lxc,vm): fix panics when a resource block is empty
  proxmoxtf/resource/container/container.go
  proxmoxtf/resource/vm/vm.go
Labels: autoapprove, size/M

#1346 fix(access): fix `user` and `role` import
  proxmoxtf/resource/role.go
  proxmoxtf/resource/user.go
Labels: autoapprove, size/M

#1347 feat(vm): allow `none` `cdrom`
  docs/resources/virtual_environment_vm.md
  example/resource_virtual_environment_vm.tf
  fwprovider/test/resource_vm_cdrom_test.go
  fwprovider/test/resource_vm_disks_test.go
  fwprovider/test/resource_vm_test.go
  proxmoxtf/resource/vm/vm.go
Labels: autoapprove, size/XXL

#1365 fix(vm): ignore 599 task status response when waiting for VM start
  example/resource_virtual_environment_container.tf
  example/resource_virtual_environment_download_file.tf
  example/variables.tf
  proxmox/nodes/tasks/tasks.go
  proxmox/nodes/vms/vms.go
  tools/go.sum
Labels: autoapprove, size/M

#1368 chore(api): refactor `nodes/vms/vms_types.go`: split into multiple files
  proxmox/nodes/vms/custom_agent.go
  proxmox/nodes/vms/custom_audio_device.go
  proxmox/nodes/vms/custom_boot.go
  proxmox/nodes/vms/custom_cloud_init.go
  proxmox/nodes/vms/custom_cpu_emulation.go
  proxmox/nodes/vms/custom_efi_disk.go
  proxmox/nodes/vms/custom_network_device.go
  proxmox/nodes/vms/custom_numa_device.go
  proxmox/nodes/vms/custom_numa_device_test.go
  proxmox/nodes/vms/custom_pci_device.go
  proxmox/nodes/vms/custom_pci_device_test.go
  proxmox/nodes/vms/custom_serial_device.go
  proxmox/nodes/vms/custom_shared_memory.go
  proxmox/nodes/vms/custom_smbios.go
  proxmox/nodes/vms/custom_spice_enhancements.go
  proxmox/nodes/vms/custom_startup_order.go
  proxmox/nodes/vms/custom_storage_device.go
  proxmox/nodes/vms/custom_storage_device_test.go
  proxmox/nodes/vms/custom_tpm_state.go
  proxmox/nodes/vms/custom_usb_device.go
  proxmox/nodes/vms/custom_usb_device_test.go
  proxmox/nodes/vms/custom_vga_device.go
  proxmox/nodes/vms/custom_virtualio_device.go
  proxmox/nodes/vms/custom_watchdog_device.go
  proxmox/nodes/vms/vms_types.go
  proxmoxtf/resource/vm/vm.go
Labels: autoapprove, size/XXL

#1370 feat(vm2): add initial support for `cdrom`
  docs/resources/virtual_environment_vm2.md
  fwprovider/access/resource_user_token.go
  fwprovider/hardwaremapping/datasource.go
  fwprovider/hardwaremapping/datasource_pci.go
  fwprovider/hardwaremapping/datasource_usb.go
  fwprovider/hardwaremapping/errors.go
  fwprovider/hardwaremapping/models.go
  fwprovider/hardwaremapping/resource_pci.go
  fwprovider/hardwaremapping/resource_usb.go
  fwprovider/hardwaremapping/shared.go
  fwprovider/validators/file.go
  fwprovider/validators/hardware_mapping.go
  fwprovider/vm/cdrom/model.go
  fwprovider/vm/cdrom/resource.go
  fwprovider/vm/cdrom/resource_schema.go
  fwprovider/vm/cdrom/resource_test.go
  fwprovider/vm/cpu/datasource_schema.go
  fwprovider/vm/cpu/model.go
  fwprovider/vm/cpu/resource.go
  fwprovider/vm/cpu/resource_schema.go
  fwprovider/vm/model.go
  fwprovider/vm/resource.go
  fwprovider/vm/resource_schema.go
  fwprovider/vm/vga/datasource_schema.go
  fwprovider/vm/vga/model.go
  fwprovider/vm/vga/resource.go
  proxmox/nodes/vms/custom_storage_device.go
  proxmox/nodes/vms/custom_storage_device_test.go
  proxmoxtf/resource/vm/disk/disk.go
  utils/maps.go
  utils/sets.go
  utils/sets_test.go
Labels: autoapprove, size/XL

#1374 chore(docs): clarify `disk.file_id` format
  docs/resources/virtual_environment_vm.md
  docs/resources/virtual_environment_vm2.md
  fwprovider/vm/cdrom/resource_schema.go
Labels: autoapprove, size/S

#1375 chore(code): fix code inspection warnings
  fwprovider/ha/resource_hagroup.go
  fwprovider/ha/resource_haresource.go
  fwprovider/test/resource_file_test.go
  proxmox/nodes/vms/custom_vga_device.go
  proxmoxtf/resource/validators/file.go
  proxmoxtf/resource/vm/vm.go
Labels: autoapprove, size/S

#1377 fix(docs): update virtual_environment_vm.md
  docs/resources/virtual_environment_vm.md
Labels: size/XS, automerge

#1382 fix(docs): add more details about the `usb` block in VM
  docs/resources/virtual_environment_vm.md
  tools/go.sum
Labels: autoapprove, size/XS

#1384 chore(code): remove goreleaser from `/tools`
  tools/go.mod
  tools/go.sum
  tools/tools.go
Labels: autoapprove, size/XXL

#1385 feat(vm): add support for `disk.serial` attribute
  docs/resources/virtual_environment_vm.md
  example/resource_virtual_environment_vm.tf
  fwprovider/test/resource_vm_disks_test.go
  proxmox/nodes/vms/custom_storage_device.go
  proxmoxtf/resource/vm/disk/disk.go
  proxmoxtf/resource/vm/disk/schema.go
Labels: autoapprove, size/M

#1386 fix(lxc): make container vm_id computed
  proxmoxtf/resource/container/container.go
Labels: size/M

#1394 chore(vm): refactor storage devices handling from/to API
  fwprovider/vm/cdrom/model.go
  fwprovider/vm/cdrom/resource.go
  proxmox/nodes/vms/custom_storage_device.go
  proxmox/nodes/vms/custom_storage_device_test.go
  proxmox/nodes/vms/vms_types.go
  proxmox/nodes/vms/vms_types_test.go
  proxmoxtf/resource/vm/disk/disk.go
  proxmoxtf/resource/vm/vm.go
  testacc
Labels: autoapprove, size/XXL

#1398 fix(lxc): use default rootfs size (4Gb) prevents creation of mount points
  example/resource_virtual_environment_container.tf
  fwprovider/test/resource_container_test.go
  proxmoxtf/resource/container/container.go
Labels: autoapprove, size/M

#1399 chore(vm): fix regression after storage devices refactoring
  proxmoxtf/resource/vm/vm.go
Labels: autoapprove, size/S

#1408 chore: refactor container acc test
  .github/workflows/test.yml
  .github/workflows/testacc.yml
  .golangci.yml
  Makefile
  fwprovider/access/resource_acl_test.go
  fwprovider/access/resource_user_test.go
  fwprovider/hardwaremapping/resource_hardware_mapping_test.go
  fwprovider/network/resource_linux_bridge_test.go
  fwprovider/network/resource_linux_vlan_test.go
  fwprovider/resource_download_file_test.go
  fwprovider/resource_options_test.go
  fwprovider/test/datasource_node_test.go
  fwprovider/test/datasource_version_test.go
  fwprovider/test/resource_container_test.go
  fwprovider/test/resource_file_test.go
  fwprovider/test/resource_firewall_test.go
  fwprovider/test/resource_time_test.go
  fwprovider/test/resource_vm_cdrom_test.go
  fwprovider/test/resource_vm_disks_test.go
  fwprovider/test/resource_vm_test.go
  fwprovider/test/test_environment.go
  fwprovider/vm/cdrom/resource_test.go
  fwprovider/vm/cpu/resource_test.go
  fwprovider/vm/resource_test.go
  fwprovider/vm/vga/resource_test.go
  proxmoxtf/resource/container/container.go
Labels: autoapprove, size/L

#1409 chore(code): fix code quality warnings
  .github/workflows/code-quality.yml
  .github/workflows/test.yml
  .github/workflows/testacc.yml
  docs/resources/virtual_environment_vm2.md
  fwprovider/ha/resource_hagroup.go
  fwprovider/ha/resource_haresource.go
  fwprovider/vm/model.go
  fwprovider/vm/resource.go
  fwprovider/vm/resource_schema.go
  proxmox/nodes/tasks/tasks.go
  proxmox/nodes/vms/custom_storage_device.go
  proxmox/nodes/vms/custom_usb_device.go
  proxmoxtf/datasource/firewall/alias.go
  proxmoxtf/datasource/firewall/alias_test.go
  proxmoxtf/datasource/firewall/aliases.go
  proxmoxtf/datasource/firewall/aliases_test.go
  proxmoxtf/datasource/firewall/ipset.go
  proxmoxtf/datasource/firewall/ipset_test.go
  proxmoxtf/datasource/firewall/ipsets.go
  proxmoxtf/datasource/firewall/ipsets_test.go
  proxmoxtf/datasource/firewall/rule.go
  proxmoxtf/datasource/firewall/rule_test.go
  proxmoxtf/datasource/firewall/security_group.go
  proxmoxtf/datasource/firewall/security_group_test.go
  proxmoxtf/datasource/firewall/security_groups.go
  proxmoxtf/datasource/firewall/security_groups_test.go
  proxmoxtf/resource/vm/vm.go
  qodana.yaml
  utils/strings.go
Labels: autoapprove, size/XL

#1407 fix(docs): Mention alternate valid use of Volid's for containers
  docs/resources/virtual_environment_container.md
Labels: size/XS
