Repository bpg/terraform-provider-proxmox, pull requests merged in 2024-09, with the labels that each got.

#1479 feat(acme): implement resources and data sources for ACME plugins
  docs/data-sources/virtual_environment_acme_plugin.md
  docs/data-sources/virtual_environment_acme_plugins.md
  docs/resources/virtual_environment_acme_dns_plugin.md
  examples/data-sources/proxmox_virtual_environment_acme_plugin/data-source.tf
  examples/data-sources/proxmox_virtual_environment_acme_plugins/data-source.tf
  examples/resources/proxmox_virtual_environment_acme_dns_plugin/import.sh
  examples/resources/proxmox_virtual_environment_acme_dns_plugin/resource.tf
  fwprovider/acme/datasource_acme_plugin.go
  fwprovider/acme/datasource_acme_plugins.go
  fwprovider/acme/plugin_model.go
  fwprovider/acme/resource_acme_dns_plugin.go
  fwprovider/provider.go
  proxmox/cluster/acme/client.go
  proxmox/cluster/acme/plugins/acme_plugins.go
  proxmox/cluster/acme/plugins/acme_plugins_types.go
  proxmox/cluster/acme/plugins/client.go
  tools/tools.go
Labels: size/XXL

#1512 feat(lxc): Implement support for container's "protection flag"
  docs/resources/virtual_environment_container.md
  example/resource_virtual_environment_container.tf
  proxmoxtf/resource/container/container.go
  proxmoxtf/resource/container/container_test.go
Labels: size/M

#1522 fix(docs): improve "SSH User" section describing `sudo` privileges
  docs/index.md
Labels: autoapprove, size/S

#1523 chore(vm): add acc test for no cdrom by default
  fwprovider/test/resource_vm_cdrom_test.go
Labels: autoapprove, size/S

#1524 fix(vm): `cpu.architecture` showed as new attribute at re-apply after creation
  proxmoxtf/resource/vm/validators.go
  proxmoxtf/resource/vm/vm.go
Labels: autoapprove, size/S

#1533 feat(vm): remove deprecated `vga.enabled`
  fwprovider/network/resource_linux_vlan_test.go
  proxmoxtf/resource/vm/vm.go
  proxmoxtf/resource/vm/vm_test.go
Labels: autoapprove, size/S

#1537 fix(file): respect `download_file.override` attr when checking for th…
  fwprovider/network/resource_linux_vlan_test.go
  fwprovider/resource_download_file.go
  fwprovider/resource_download_file_test.go
Labels: autoapprove, size/L

#1538 chore(docs): improve `network_linux_bridge` documentation
  docs/resources/virtual_environment_network_linux_bridge.md
  examples/resources/proxmox_virtual_environment_network_linux_bridge/resource.tf
Labels: autoapprove, size/S

#1543 fix(vm): handle more than 4 `hostpci` devices
  docs/resources/virtual_environment_vm.md
  fwprovider/vm/cdrom/resource.go
  proxmox/nodes/vms/custom_pci_device.go
  proxmox/nodes/vms/vms_types.go
  proxmox/nodes/vms/vms_types_test.go
  proxmoxtf/resource/vm/disk/disk.go
  proxmoxtf/resource/vm/vm.go
Labels: autoapprove, size/L, acknowledged

#1547 chore(docs): add example for host disk pass-through to VM
  docs/resources/virtual_environment_vm.md
Labels: autoapprove, size/M

#1548 chore(lxc): update list of supported OS-es in `operating_system.type`
  docs/resources/virtual_environment_container.md
  proxmoxtf/resource/container/validators.go
Labels: autoapprove, size/S

#1550 fix(docs): document specifics of "ballooning device" in the `vm.memor…
  docs/resources/virtual_environment_vm.md
Labels: autoapprove, size/S

#1553 fix(lxc): add new storage-backed mount point to existing container
  fwprovider/test/resource_container_test.go
  proxmoxtf/resource/container/container.go
Labels: autoapprove, size/M
