Repository bpg/terraform-provider-proxmox, pull requests merged in 2024-07, with the labels that each got.

#1423 feat(vm): implement filtering in vms data source.
  .github/workflows/code-quality.yml
  docs/data-sources/virtual_environment_vm.md
  docs/data-sources/virtual_environment_vms.md
  example/data_source_virtual_environment_vms.tf
  proxmox/nodes/vms/vms_types.go
  proxmoxtf/datasource/vm.go
  proxmoxtf/datasource/vm_test.go
  proxmoxtf/datasource/vms.go
  proxmoxtf/datasource/vms_test.go
Labels: size/L

#1325 feat(node): implement initial support to manage APT repositories
  .golangci.yml
  docs/data-sources/virtual_environment_apt_repository.md
  docs/data-sources/virtual_environment_apt_standard_repository.md
  docs/resources/virtual_environment_apt_repository.md
  docs/resources/virtual_environment_apt_standard_repository.md
  examples/data-sources/proxmox_virtual_environment_apt_repository/data-source.tf
  examples/data-sources/proxmox_virtual_environment_apt_standard_repository/data-source.tf
  examples/resources/proxmox_virtual_environment_apt_repository/import.sh
  examples/resources/proxmox_virtual_environment_apt_repository/resource.tf
  examples/resources/proxmox_virtual_environment_apt_standard_repository/import.sh
  examples/resources/proxmox_virtual_environment_apt_standard_repository/resource.tf
  fwprovider/nodes/apt/datasource_repo.go
  fwprovider/nodes/apt/datasource_standard_repo.go
  fwprovider/nodes/apt/models.go
  fwprovider/nodes/apt/repo_test.go
  fwprovider/nodes/apt/resource_repo.go
  fwprovider/nodes/apt/resource_standard_repo.go
  fwprovider/provider.go
  fwprovider/types/nodes/apt/errors.go
  fwprovider/types/nodes/apt/standard_repo_handle.go
  fwprovider/types/nodes/apt/standard_repo_handle_test.go
  fwprovider/validators/strings.go
  proxmox/nodes/apt/client.go
  proxmox/nodes/apt/repositories/repositories.go
  proxmox/nodes/apt/repositories/types.go
  proxmox/nodes/client.go
  proxmox/nodes/network.go
  proxmox/types/nodes/apt/repositories/ceph_version_name.go
  proxmox/types/nodes/apt/repositories/errors.go
  proxmox/types/nodes/apt/repositories/standard_repo_file_path.go
  proxmox/types/nodes/apt/repositories/standard_repo_handle_kind.go
  tools/tools.go
Labels: size/XXL

#1431 fix(vm): improve reliability of VM create / get operations
  fwprovider/nodes/apt/repo_test.go
  fwprovider/test/test_environment.go
  fwprovider/vm/resource_test.go
  proxmox/api/client.go
  proxmox/nodes/vms/vms.go
  testacc
Labels: autoapprove, size/M

#1436 fix(time): embed timezone data to fix set/get TZ on windows
  fwprovider/test/resource_time_test.go
  proxmoxtf/resource/time.go
Labels: autoapprove, size/XS

#1438 fix(vm): panic when reading VM with SPICE USB passthrough
  proxmox/nodes/vms/custom_usb_device.go
  proxmox/nodes/vms/custom_usb_device_test.go
Labels: autoapprove, size/XS

#1442 fix(docs): document role privileges required by `proxmox_virtual_environment_download_file`
  docs/index.md
  docs/resources/virtual_environment_download_file.md
  templates/resources/virtual_environment_download_file.md.tmpl
Labels: size/M
