Repository bpg/terraform-provider-proxmox, pull requests merged in 2024-11, with the labels that each got.

#1607 fix(cluster): `insecure` `migration_type` validation
  docs/resources/virtual_environment_cluster_options.md
  fwprovider/resource_options.go
Labels: size/XS

#1611 feat(cpu type): CPU type support for EPYC-v4
  docs/resources/virtual_environment_vm.md
  fwprovider/vm/cpu/resource_schema.go
  proxmoxtf/resource/vm/validators.go
Labels: size/XS

#1635 chore(docs): clarify use of `dump` content type in`proxmox_virtual_environment_file` resource
  docs/resources/virtual_environment_file.md
Labels: autoapprove, size/XS

#1644 chore(ci): remove semgrep workflow
  .github/workflows/semgrep.yml
Labels: autoapprove, size/S

#1645 feat(provider): better error logging when provider can't generate a VM/Container ID
  proxmox/cluster/id_generator.go
Labels: autoapprove, size/XS

#1647 fix(provider): "context deadline exceeded" error when retrieving the next available VM identifier
  fwprovider/provider_test.go
  proxmox/cluster/id_generator.go
Labels: autoapprove, size/M

#1652 chore(ci): remove mergify config
  .mergify.yml
Labels: autoapprove, size/S

#1653 chore(ci): update qodana config
  qodana.yaml
Labels: autoapprove, size/XS

#1655 feat(vm): add bz2 (bzip2) as a valid download file compression algorithm
  docs/resources/virtual_environment_download_file.md
  fwprovider/resource_download_file.go
Labels: size/XS

#1482 feat(node): add support for node config API
  proxmox/nodes/config.go
  proxmox/nodes/config_types.go
  proxmox/nodes/config_types_test.go
Labels: autoapprove, size/XL

#1663 chore(docs): update README.md to PVE 8.3
  README.md
Labels: autoapprove, size/XS
