Repository bpg/terraform-provider-proxmox, pull requests merged in 2024-02, with the labels that each got.

#991 fix(vm): update disk size to 0 vmReadCustom
  proxmoxtf/resource/vm.go
Labels: size/XS

#1001 docs: update sudo configuration to a more restrictive variant
  docs/index.md
Labels: size/XS

#1004 fix(file): use `sudo` for snippets upload
  .vscode/settings.json
  docs/index.md
  proxmoxtf/resource/file.go
  proxmoxtf/resource/sudo.go
  proxmoxtf/resource/vm.go
Labels: autoapprove, size/M

#1013 fix: snippets upload
  proxmoxtf/resource/file.go
Labels: size/XS

#1023 chore(ci): update mergify config to auto-approve renovate PRs
  .golangci.yml
  .mergify.yml
Labels: autoapprove, size/S

#1024 misc(ci): update .mergify.yml
  .mergify.yml
Labels: autoapprove, size/S

#1028 chore(docs): update links disk image link in examples
  examples/guides/cloud-image/centos-qcow2/main.tf
  examples/guides/cloud-image/ubuntu-img/main.tf
Labels: autoapprove, size/XS

#1030 fix(vm): multi-line description field is always marked as changed
  .vscode/settings.json
  fwprovider/tests/resource_container_test.go
  fwprovider/tests/resource_file_test.go
  proxmox/api/client.go
  proxmox/ssh/client.go
  proxmoxtf/resource/container.go
  proxmoxtf/resource/file.go
  proxmoxtf/resource/sudo.go
  proxmoxtf/resource/vm.go
Labels: autoapprove, size/L

#1033 fix(vm): fix panic when a config block is empty
  proxmoxtf/resource/vm.go
Labels: autoapprove, size/M

#1040 chore(vm): refactoring, add acceptance tests
  .devcontainer/devcontainer.json
  .golangci.yml
  .vscode/launch.json
  .vscode/settings.json
  example/resource_virtual_environment_file.tf
  example/resource_virtual_environment_vm.tf
  fwprovider/tests/resource_container_test.go
  fwprovider/tests/resource_download_file_test.go
  fwprovider/tests/resource_linux_bridge_test.go
  fwprovider/tests/resource_linux_vlan_test.go
  fwprovider/tests/resource_vm_test.go
  proxmox/api/client.go
  proxmox/nodes/containers/containers_types.go
  proxmox/nodes/tasks/tasks_types_test.go
  proxmox/nodes/vms/customstoragedevice.go
  proxmox/nodes/vms/vms.go
  proxmox/nodes/vms/vms_types.go
  proxmox/nodes/vms/vms_types_test.go
  proxmox/types/common_types.go
  proxmox/types/disk_size.go
  proxmox/types/disk_size_test.go
  proxmox/types/helpers.go
  proxmoxtf/resource/container.go
  proxmoxtf/resource/file.go
  proxmoxtf/resource/vm.go
  utils/strings.go
Labels: autoapprove, size/XXL

#1042 fix(lxc): panic when handling `network_interface.firewall` attribute
  .vscode/settings.json
  proxmoxtf/resource/container.go
Labels: autoapprove, size/M

#1043 fix(lxc): panic on empty `initialization.ip_config.ipv4|6` block
  proxmoxtf/resource/container.go
Labels: autoapprove, size/XS

#1045 chore(docs): update README.md
  .markdownlint.json
  .vscode/settings.json
  README.md
  tools/go.mod
Labels: autoapprove, size/S

#1046 chore(lxc,vm): refactor: move vm and container code to subpackages
  .golangci.yml
  .vscode/settings.json
  proxmoxtf/provider/resources.go
  proxmoxtf/resource/container/container.go
  proxmoxtf/resource/container/container_test.go
  proxmoxtf/resource/container/validators.go
  proxmoxtf/resource/container_test.go
  proxmoxtf/resource/firewall/selector.go
  proxmoxtf/resource/validator/container.go
  proxmoxtf/resource/validator/file.go
  proxmoxtf/resource/vm/validators.go
  proxmoxtf/resource/vm/validators_test.go
  proxmoxtf/resource/vm/vm.go
  proxmoxtf/resource/vm/vm_test.go
  proxmoxtf/resource/vm_test.go
Labels: autoapprove, size/XXL

#1049 fix(vm): regression: `mac_addresses` list is missing some interfaces
  .vscode/launch.json
  fwprovider/tests/resource_vm_test.go
  proxmoxtf/resource/container/container.go
  proxmoxtf/resource/vm/vm.go
Labels: autoapprove, size/M

#1052 fix(provider): race condition in`~/.ssh` path existence check
  proxmox/ssh/client.go
Labels: size/XS

#1062 chore(vm): refactor: move disks code out of vm.go
  .golangci.yml
  fwprovider/tests/resource_vm_test.go
  proxmoxtf/resource/cluster/firewall/firewall.go
  proxmoxtf/resource/container/container.go
  proxmoxtf/resource/file.go
  proxmoxtf/resource/firewall/options.go
  proxmoxtf/resource/firewall/rules.go
  proxmoxtf/resource/validators/file.go
  proxmoxtf/resource/validators/file_test.go
  proxmoxtf/resource/validators/firewall.go
  proxmoxtf/resource/validators/network.go
  proxmoxtf/resource/validators/network_test.go
  proxmoxtf/resource/vm/disk/disk.go
  proxmoxtf/resource/vm/disk/schema.go
  proxmoxtf/resource/vm/vm.go
  proxmoxtf/resource/vm/vm_test.go
  utils/maps.go
Labels: autoapprove, size/XXL

#1064 feat(file): add `overwrite_unmanaged` attribute to `virtual_environment_download_file` resource
  .github/workflows/golangci-lint.yml
  .github/workflows/test.yml
  docs/guides/cloud-image.md
  docs/resources/virtual_environment_download_file.md
  example/resource_virtual_environment_download_file.tf
  fwprovider/resource_download_file.go
  fwprovider/tests/resource_download_file_test.go
  fwprovider/tests/resource_file_test.go
  fwprovider/tests/resource_vm_test.go
  fwprovider/tests/test_support.go
  templates/guides/cloud-image.md.tmpl
  templates/guides/cloud-init.md.tmpl
  templates/guides/setup-proxmox-for-tests.md.tmpl
Labels: autoapprove, size/L

#1066 fix(user): `expiration_date` attribute handling
  .golangci.yml
  example/resource_virtual_environment_user.tf
  fwprovider/tests/resource_container_test.go
  fwprovider/tests/resource_download_file_test.go
  fwprovider/tests/resource_linux_bridge_test.go
  fwprovider/tests/resource_linux_vlan_test.go
  fwprovider/tests/resource_user_test.go
  fwprovider/tests/resource_vm_test.go
  proxmox/access/users.go
  proxmox/access/users_types.go
  proxmoxtf/datasource/user.go
  proxmoxtf/datasource/users.go
  proxmoxtf/resource/user.go
Labels: autoapprove, size/L

#1067 chore: switch to `terraform-plugin-testing` for acceptance tests
  fwprovider/tests/datasource_version_test.go
  fwprovider/tests/resource_container_test.go
  fwprovider/tests/resource_download_file_test.go
  fwprovider/tests/resource_file_test.go
  fwprovider/tests/resource_linux_bridge_test.go
  fwprovider/tests/resource_linux_vlan_test.go
  fwprovider/tests/resource_options_test.go
  fwprovider/tests/resource_user_test.go
  fwprovider/tests/resource_vm_test.go
  fwprovider/tests/test_support.go
  go.mod
  go.sum
Labels: autoapprove, size/S

#1071 chore(ci): setup acceptance tests
  .github/workflows/test.yml
  Makefile
  fwprovider/tests/resource_container_test.go
  fwprovider/tests/resource_download_file_test.go
  fwprovider/tests/resource_file_test.go
  fwprovider/tests/resource_vm_test.go
  fwprovider/tests/test_support.go
Labels: autoapprove, size/L
