Repository bpg/terraform-provider-proxmox, pull requests merged in 2024-04, with the labels that each got.

#1182 fix(vm): regressions: provider always tries to update `cpu.affinity` even if it is not specified
  .vscode/settings.json
  fwprovider/tests/resource_vm_test.go
  proxmoxtf/resource/vm/vm.go
Labels: autoapprove, size/M

#1188 fix(vm): regression: provider always tries to update `memory.*hugepages` even if it is not specified
  fwprovider/tests/resource_vm_test.go
  proxmoxtf/resource/vm/vm.go
  testacc
Labels: autoapprove, size/M

#1173 chore: improve acceptance tests on CI
  .github/workflows/test.yml
  .github/workflows/testacc.yml
  CONTRIBUTING.md
  fwprovider/tests/datasource_node_test.go
  fwprovider/tests/datasource_version_test.go
  fwprovider/tests/resource_container_test.go
  fwprovider/tests/resource_download_file_test.go
  fwprovider/tests/resource_file_test.go
  fwprovider/tests/resource_linux_bridge_test.go
  fwprovider/tests/resource_linux_vlan_test.go
  fwprovider/tests/resource_options_test.go
  fwprovider/tests/resource_user_test.go
  fwprovider/tests/resource_vm_test.go
  fwprovider/tests/test_environment.go
  fwprovider/tests/test_support.go
  proxmox/nodes/query_url_metadata.go
  utils/env.go
Labels: autoapprove, size/XL

#1195 chore: refactor acceptance tests
  .vscode/settings.json
  fwprovider/tests/datasource_node_test.go
  fwprovider/tests/datasource_version_test.go
  fwprovider/tests/resource_container_test.go
  fwprovider/tests/resource_download_file_test.go
  fwprovider/tests/resource_file_test.go
  fwprovider/tests/resource_linux_bridge_test.go
  fwprovider/tests/resource_linux_vlan_test.go
  fwprovider/tests/resource_user_test.go
  fwprovider/tests/resource_vm_test.go
  fwprovider/tests/test_environment.go
Labels: autoapprove, size/XL

#1196 fix(vm): panic if `numa` block is empty
  utils/maps.go
  utils/maps_test.go
Labels: autoapprove, size/M

#1197 fix(vm): panic if `initialization.user_account_keys` contains `null`
  proxmoxtf/resource/vm/vm.go
Labels: autoapprove, size/XS

#1199 fix(firewall): remove strict validation for `rule.iface` attribute
  fwprovider/tests/resource_firewall_test.go
  proxmoxtf/resource/firewall/rules.go
Labels: autoapprove, size/M

#1200 chore(docs): minor documentation updates
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  docs/resources/virtual_environment_file.md
Labels: autoapprove, size/S

#1203 feat(vm): add support for `initialization.upgrade` attribute
  docs/resources/virtual_environment_vm.md
  fwprovider/tests/resource_vm_test.go
  proxmox/nodes/vms/vms_types.go
  proxmoxtf/resource/vm/vm.go
Labels: autoapprove, size/M

#1206 fix(vm): error 'resizing of efidisks is not supported' when clonning a VM with re-defined `efi_disk`
  example/resource_virtual_environment_vm.tf
  proxmoxtf/resource/vm/vm.go
Labels: size/XS

#1209 fix(vm): regression: force VM recreation due to `initialization.upgrade` when it is not in the plan
  proxmoxtf/resource/vm/vm.go
Labels: autoapprove, size/S

#1215 fix(vm): state drift due to disk re-ordering
  .vscode/extensions.json
  .vscode/settings.json
  fwprovider/tests/resource_vm_test.go
  proxmox/nodes/storage/download_url.go
  proxmoxtf/resource/vm/disk/disk.go
  proxmoxtf/resource/vm/disk/schema.go
  proxmoxtf/resource/vm/vm.go
  proxmoxtf/structure/schema.go
  utils/maps.go
Labels: autoapprove, size/L

#1218 chore(code): reorganize HA & node network code
  fwprovider/ha/datasource_hagroup.go
  fwprovider/ha/datasource_hagroups.go
  fwprovider/ha/datasource_haresource.go
  fwprovider/ha/datasource_haresources.go
  fwprovider/ha/hagroup_model.go
  fwprovider/ha/haresource_model.go
  fwprovider/ha/resource_hagroup.go
  fwprovider/ha/resource_haresource.go
  fwprovider/ha/validators.go
  fwprovider/network/resource_linux_bridge.go
  fwprovider/network/resource_linux_vlan.go
  fwprovider/provider.go
  fwprovider/validators/ha_resource_validator.go
Labels: autoapprove, size/L

#1213 feat(cluster): Implement initial support for "hardware mappings"
  .golangci.yml
  README.md
  docs/data-sources/virtual_environment_hardware_mapping_pci.md
  docs/data-sources/virtual_environment_hardware_mapping_usb.md
  docs/data-sources/virtual_environment_hardware_mappings.md
  docs/resources/virtual_environment_hardware_mapping_pci.md
  docs/resources/virtual_environment_hardware_mapping_usb.md
  examples/data-sources/proxmox_virtual_environment_hardware_mapping_pci/data-source.tf
  examples/data-sources/proxmox_virtual_environment_hardware_mapping_usb/data-source.tf
  examples/data-sources/proxmox_virtual_environment_hardware_mappings/data-source.tf
  examples/resources/proxmox_virtual_environment_hardware_mapping_pci/import.sh
  examples/resources/proxmox_virtual_environment_hardware_mapping_pci/resource.tf
  examples/resources/proxmox_virtual_environment_hardware_mapping_usb/import.sh
  examples/resources/proxmox_virtual_environment_hardware_mapping_usb/resource.tf
  fwprovider/hardwaremapping/datasource.go
  fwprovider/hardwaremapping/datasource_pci.go
  fwprovider/hardwaremapping/datasource_usb.go
  fwprovider/hardwaremapping/errors.go
  fwprovider/hardwaremapping/models.go
  fwprovider/hardwaremapping/resource_pci.go
  fwprovider/hardwaremapping/resource_usb.go
  fwprovider/hardwaremapping/shared.go
  fwprovider/provider.go
  fwprovider/tests/resource_hardware_mapping_test.go
  fwprovider/types/hardwaremapping/path.go
  fwprovider/types/hardwaremapping/path_test.go
  fwprovider/validators/hardware_mapping.go
  proxmox/cluster/client.go
  proxmox/cluster/ha/resources/api.http
  proxmox/cluster/ha/resources/http-client.env.json
  proxmox/cluster/ha/resources/http-client.private.env.json
  proxmox/cluster/mapping/client.go
  proxmox/cluster/mapping/mapping.go
  proxmox/cluster/mapping/types.go
  proxmox/types/hardwaremapping/device_id.go
  proxmox/types/hardwaremapping/errors.go
  proxmox/types/hardwaremapping/id.go
  proxmox/types/hardwaremapping/map.go
  proxmox/types/hardwaremapping/type.go
  tools/tools.go
Labels: size/XXL

#1223 chore(vm): fix acceptance test for hardware mapping
  fwprovider/tests/resource_hardware_mapping_test.go
Labels: autoapprove, size/S

#1222 fix(vm,lxc,file): improve timeouts handling
  docs/resources/virtual_environment_container.md
  docs/resources/virtual_environment_vm.md
  fwprovider/resource_download_file.go
  fwprovider/tests/datasource_node_test.go
  fwprovider/tests/resource_container_test.go
  fwprovider/tests/resource_download_file_test.go
  proxmox/api/client.go
  proxmox/api/client_test.go
  proxmox/api/errors.go
  proxmox/nodes/containers/containers.go
  proxmox/nodes/network.go
  proxmox/nodes/storage/content.go
  proxmox/nodes/storage/download_url.go
  proxmox/nodes/storage/upload.go
  proxmox/nodes/tasks/tasks.go
  proxmox/nodes/vms/vms.go
  proxmox/nodes/vms/vms_types.go
  proxmoxtf/datasource/vm.go
  proxmoxtf/resource/container/container.go
  proxmoxtf/resource/file.go
  proxmoxtf/resource/group.go
  proxmoxtf/resource/pool.go
  proxmoxtf/resource/role.go
  proxmoxtf/resource/user.go
  proxmoxtf/resource/vm/disk/disk.go
  proxmoxtf/resource/vm/disk/schema.go
  proxmoxtf/resource/vm/vm.go
Labels: autoapprove, size/XXL

#1230 chore(vm2): initial experimental VM resource implementation using Plugin Framework
  docs/resources/virtual_environment_vm2.md
  fwprovider/provider.go
  fwprovider/tests/resource_vm2_test.go
  fwprovider/vm/resource.go
  fwprovider/vm/resource_model.go
  fwprovider/vm/resource_schema.go
  go.mod
  go.sum
  proxmox/nodes/vms/vms_types.go
  proxmox/types/helpers.go
  templates/resources/virtual_environment_vm2.md.tmpl
  tools/tools.go
Labels: autoapprove, size/XL

#1232 chore(vm2): experiment with sets, add `tags` support
  docs/resources/virtual_environment_vm2.md
  fwprovider/tests/resource_vm2_test.go
  fwprovider/types/hardwaremapping/path.go
  fwprovider/types/tags/attribute.go
  fwprovider/types/tags/type.go
  fwprovider/types/tags/value.go
  fwprovider/vm/resource.go
  fwprovider/vm/resource_model.go
  fwprovider/vm/resource_schema.go
Labels: autoapprove, size/L

#1236 chore: remove unused code
  .github/workflows/code-quality.yml
  README.md
  fwprovider/provider.go
  fwprovider/tests/resource_container_test.go
  proxmox/types/helpers.go
  proxmoxtf/datasource/cluster/firewall.go
  proxmoxtf/datasource/firewall/security_group.go
  proxmoxtf/datasource/firewall/security_groups.go
  proxmoxtf/datasource/node.go
  proxmoxtf/provider/schema.go
  proxmoxtf/resource/container/container.go
  proxmoxtf/resource/file.go
  proxmoxtf/resource/group.go
  proxmoxtf/resource/pool.go
  proxmoxtf/resource/role.go
  proxmoxtf/resource/user.go
  proxmoxtf/resource/validators/firewall.go
  proxmoxtf/resource/vm/network/schema.go
  proxmoxtf/resource/vm/vm.go
  qodana.yaml
Labels: autoapprove, size/L

#1241 feat(cluster): Extend the available attributes for the `proxmox_virtual_environment_cluster_options` resource
  docs/resources/virtual_environment_cluster_options.md
  examples/resources/proxmox_virtual_environment_cluster_options/resource.tf
  fwprovider/resource_options.go
  fwprovider/tests/resource_options_test.go
  proxmox/cluster/options_types.go
Labels: size/L

#1237 feat(vm): add initial support for IDE
  example/resource_virtual_environment_vm.tf
  fwprovider/tests/resource_vm_test.go
  proxmoxtf/resource/vm/disk/disk.go
  proxmoxtf/resource/vm/vm.go
Labels: :hourglass: pending author's response, size/L
