Repository bpg/terraform-provider-proxmox, pull requests merged in 2024-10, with the labels that each got.

#1558 fix(provider): handle IPv6 in ssh client
  proxmox/ssh/client.go
Labels: size/XS

#1563 fix(docs): correct url for template download in container resource example
  docs/resources/virtual_environment_container.md
Labels: size/XS

#1557 feat(provider): reliable sequential and random `vm_id` generation
  .vscode/extensions.json
  .vscode/settings.json
  docs/index.md
  fwprovider/access/resource_acl.go
  fwprovider/access/resource_user_token.go
  fwprovider/acme/datasource_acme_account.go
  fwprovider/acme/datasource_acme_accounts.go
  fwprovider/acme/datasource_acme_plugin.go
  fwprovider/acme/datasource_acme_plugins.go
  fwprovider/acme/resource_acme_account.go
  fwprovider/acme/resource_acme_dns_plugin.go
  fwprovider/config/datasource.go
  fwprovider/config/doc.go
  fwprovider/config/resource.go
  fwprovider/datasource_version.go
  fwprovider/ha/datasource_hagroup.go
  fwprovider/ha/datasource_hagroups.go
  fwprovider/ha/datasource_haresource.go
  fwprovider/ha/datasource_haresources.go
  fwprovider/ha/resource_hagroup.go
  fwprovider/ha/resource_haresource.go
  fwprovider/hardwaremapping/datasource.go
  fwprovider/hardwaremapping/datasource_pci.go
  fwprovider/hardwaremapping/datasource_usb.go
  fwprovider/hardwaremapping/resource_pci.go
  fwprovider/hardwaremapping/resource_usb.go
  fwprovider/network/resource_linux_bridge.go
  fwprovider/network/resource_linux_vlan.go
  fwprovider/nodes/apt/datasource_repo.go
  fwprovider/nodes/apt/datasource_standard_repo.go
  fwprovider/nodes/apt/resource_repo.go
  fwprovider/nodes/apt/resource_standard_repo.go
  fwprovider/provider.go
  fwprovider/resource_download_file.go
  fwprovider/resource_options.go
  fwprovider/test/resource_container_test.go
  fwprovider/test/test_environment.go
  fwprovider/vm/cdrom/resource_test.go
  fwprovider/vm/cpu/resource_test.go
  fwprovider/vm/datasource.go
  fwprovider/vm/resource.go
  fwprovider/vm/resource_test.go
  fwprovider/vm/vga/resource_test.go
  go.mod
  go.sum
  proxmox/cluster/cluster.go
  proxmox/cluster/id_generator.go
  proxmoxtf/config.go
  proxmoxtf/provider/provider.go
  proxmoxtf/provider/schema.go
  proxmoxtf/resource/container/container.go
  proxmoxtf/resource/vm/vm.go
Labels: autoapprove, size/XL

#1566 fix:typo in container guide
  docs/resources/virtual_environment_container.md
Labels: size/XS

#1574 fix(provider): sequentially generated `vm_id`s may clash with exiting…
  fwprovider/provider_test.go
  fwprovider/test/test_environment.go
  proxmox/cluster/id_generator.go
Labels: autoapprove, size/L

#1578 fix(docs): update README.md
  README.md
Labels: autoapprove, size/XS

#1580 fix(vm): do not reboot at disk resize
  proxmox/helpers/ptr/ptr.go
  proxmoxtf/resource/vm/disk/disk.go
  proxmoxtf/resource/vm/vm.go
Labels: autoapprove, size/S

#1584 fix(docs): typo in cloud-image.md guide, exiting -> existing
  docs/guides/cloud-image.md
  templates/guides/cloud-image.md.tmpl
Labels: size/XS, automerge

#1591 misc(docs): minor project docs update
  .github/FUNDING.yml
  .github/ISSUE_TEMPLATE/bug_report.md
  README.md
Labels: autoapprove, size/S

#1562 chore(tests): add script to test/view api-authentication successes/failures
  Makefile
  example/test-api-creds-auth/.gitignore
  example/test-api-creds-auth/api-creds-tester.sh
  example/test-api-creds-auth/data_object.tf
  example/test-api-creds-auth/main.tf
  example/test-api-creds-auth/variables.tf
  example/test-api-creds-auth/versions.tf
Labels: size/XL, automerge

#1596 fix(tests): add missing example.tfrc to test api-authentication folder
  example/test-api-creds-auth/example.tfrc
Labels: size/XS

#1602 fix(vm): incorrect detection of disk resize
  proxmoxtf/resource/vm/vm.go
Labels: autoapprove, size/M
