Repository bpg/terraform-provider-proxmox, pull requests merged in 2024-08, with the labels that each got.

#1463 chore(docs): minor documentation updates
  README.md
  docs/index.md
Labels: autoapprove, size/M

#1464 fix(tools): ensure docs/guides files are copied correctly
  tools/tools.go
Labels: size/XS

#1468 fix(storage): ignore `os.ErrClosed` from deferred `fileReader.Close()` in storage.APIUpload
  proxmox/nodes/storage/upload.go
Labels: size/XS

#1455 feat(acme): implement resources and data sources for ACME accounts
  docs/data-sources/virtual_environment_acme_account.md
  docs/data-sources/virtual_environment_acme_accounts.md
  docs/index.md
  docs/resources/virtual_environment_acme_account.md
  examples/data-sources/proxmox_virtual_environment_acme_account/data-source.tf
  examples/data-sources/proxmox_virtual_environment_acme_accounts/data-source.tf
  examples/resources/proxmox_virtual_environment_acme_account/import.sh
  examples/resources/proxmox_virtual_environment_acme_account/resource.tf
  fwprovider/acme/datasource_acme_account.go
  fwprovider/acme/datasource_acme_accounts.go
  fwprovider/acme/resource_acme_account.go
  fwprovider/provider.go
  proxmox/cluster/acme/account/acme_account.go
  proxmox/cluster/acme/account/acme_account_types.go
  proxmox/cluster/acme/account/client.go
  proxmox/cluster/acme/client.go
  proxmox/cluster/client.go
  tools/tools.go
Labels: size/XXL

#1481 feat(devcontainer): configure provider override in post attach command
  .devcontainer/devcontainer.json
  .devcontainer/post-attach.sh
Labels: size/S

#1487 fix(firewall): remove limit for number of CIRDs in `ipset`.
  proxmoxtf/resource/firewall/ipset.go
Labels: autoapprove, size/XS

#1488 chore(code): align resource/datasource names in the fwprovider code
  fwprovider/hardwaremapping/datasource_pci.go
  fwprovider/hardwaremapping/datasource_usb.go
  fwprovider/hardwaremapping/resource_pci.go
  fwprovider/hardwaremapping/resource_usb.go
  fwprovider/nodes/apt/datasource_repo.go
  fwprovider/nodes/apt/datasource_standard_repo.go
  fwprovider/nodes/apt/resource_repo.go
  fwprovider/nodes/apt/resource_standard_repo.go
  fwprovider/provider.go
Labels: autoapprove, size/L

#1478 feat(file): add support to set the file mode
  docs/resources/virtual_environment_container.md
  docs/resources/virtual_environment_file.md
  docs/resources/virtual_environment_vm.md
  proxmox/api/client_types.go
  proxmox/ssh/client.go
  proxmoxtf/resource/file.go
  proxmoxtf/resource/file_test.go
  proxmoxtf/resource/validators/file.go
  proxmoxtf/resource/validators/file_test.go
Labels: size/L

#1495 fix(doc): update virtual_environment_vm.md
  docs/resources/virtual_environment_vm.md
Labels: size/XS, automerge

#1497 chore(example): update links to container images, use faster mirror
  example/resource_virtual_environment_container.tf
  example/resource_virtual_environment_download_file.tf
  example/variables.tf
Labels: autoapprove, size/S
