Repository bpg/terraform-provider-proxmox, pull requests merged in 2025-04, with the labels that each got.

#1875 feat(datastores)!: implement new structured format and filters for `datastores` data source
  docs/data-sources/virtual_environment_datastores.md
  fwprovider/access/resource_acl.go
  fwprovider/access/resource_user_token.go
  fwprovider/attribute/attribute.go
  fwprovider/cluster/ha/datasource_hagroup.go
  fwprovider/cluster/ha/datasource_hagroups.go
  fwprovider/cluster/ha/datasource_haresource.go
  fwprovider/cluster/ha/datasource_haresources.go
  fwprovider/cluster/ha/resource_hagroup.go
  fwprovider/cluster/ha/resource_haresource.go
  fwprovider/cluster/metrics/datasource_metrics_server.go
  fwprovider/cluster/metrics/resource_metrics_server.go
  fwprovider/cluster/options/resource_options.go
  fwprovider/nodes/apt/datasource_repo.go
  fwprovider/nodes/apt/datasource_standard_repo.go
  fwprovider/nodes/apt/resource_repo.go
  fwprovider/nodes/apt/resource_standard_repo.go
  fwprovider/nodes/datastores/datasource.go
  fwprovider/nodes/datastores/datasource_schema.go
  fwprovider/nodes/datastores/datasource_test.go
  fwprovider/nodes/datastores/model.go
  fwprovider/nodes/hardwaremapping/datasource.go
  fwprovider/nodes/hardwaremapping/datasource_pci.go
  fwprovider/nodes/hardwaremapping/datasource_usb.go
  fwprovider/nodes/hardwaremapping/resource_pci.go
  fwprovider/nodes/hardwaremapping/resource_usb.go
  fwprovider/nodes/network/resource_linux_bridge.go
  fwprovider/nodes/network/resource_linux_vlan.go
  fwprovider/nodes/resource_download_file.go
  fwprovider/nodes/vm/model.go
  fwprovider/provider.go
  fwprovider/types/stringset/attribute.go
  fwprovider/types/stringset/options.go
  fwprovider/types/stringset/value.go
  main.go
  proxmox/nodes/storage/storage_types.go
  proxmox/types/common_types.go
  proxmoxtf/datasource/datastores.go
  proxmoxtf/datasource/datastores_test.go
  proxmoxtf/provider/datasources.go
Labels: autoapprove, size/XL

#1883 misc(datastores): update datasource references in `/example`
  example/data_source_virtual_environment_datastores.tf
  example/resource_virtual_environment_container.tf
  example/resource_virtual_environment_file.tf
  example/resource_virtual_environment_vm.tf
Labels: autoapprove, size/M

#1884 chore(vm)!: remove deprecated `initialization.dns.server`, `initialization.upgrade`
  proxmoxtf/resource/vm/vm.go
  proxmoxtf/resource/vm/vm_test.go
Labels: autoapprove, size/M

#1885 feat(vm): do not force VM re-create on `initialization.user_account` changes
  fwprovider/test/resource_vm_test.go
  proxmox/nodes/vms/vms.go
  proxmoxtf/resource/vm/vm.go
Labels: autoapprove, size/M

#1886 chore(docs): add known issue to the README about Debian 12 VM requiring a serial device
  README.md
Labels: autoapprove, size/S

#1891 misc(docs): add Brian King as a sponsor in the README
  README.md
Labels: autoapprove, size/XS

#1897 fix(vm): edge case error when cloning a VM with EFI disk
  proxmoxtf/resource/vm/vm.go
Labels: autoapprove, size/XS

#1899 chore(docs): indicate support of Proxmox VE 8.4
  CONTRIBUTING.md
  README.md
  fwprovider/test/datasource_version_test.go
Labels: autoapprove, size/S

#1906 chore(vm): add an acc test for `disk.backup` update edge case
  fwprovider/test/resource_vm_disks_test.go
Labels: autoapprove, size/XS

#1900 feat(vm): add support for `virtiofs`
  docs/resources/virtual_environment_vm.md
  example/resource_virtual_environment_vm.tf
  fwprovider/test/resource_vm_test.go
  proxmox/nodes/vms/custom_virtiofs_share.go
  proxmox/nodes/vms/custom_virtiofs_share_test.go
  proxmox/nodes/vms/vms_types.go
  proxmox/nodes/vms/vms_types_test.go
  proxmoxtf/resource/vm/validators.go
  proxmoxtf/resource/vm/vm.go
  proxmoxtf/resource/vm/vm_test.go
Labels: size/L

#1902 feat(hardwaremapping): Introduce support for directory mappings
  docs/data-sources/virtual_environment_hardware_mapping_dir.md
  docs/data-sources/virtual_environment_hardware_mappings.md
  docs/resources/virtual_environment_hardware_mapping_dir.md
  example/resource_virtual_environment_vm.tf
  examples/data-sources/proxmox_virtual_environment_hardware_mapping_dir/data-source.tf
  examples/data-sources/proxmox_virtual_environment_hardware_mappings/data-source.tf
  examples/resources/proxmox_virtual_environment_hardware_mapping_dir/import.sh
  examples/resources/proxmox_virtual_environment_hardware_mapping_dir/resource.tf
  fwprovider/nodes/hardwaremapping/datasource.go
  fwprovider/nodes/hardwaremapping/datasource_dir.go
  fwprovider/nodes/hardwaremapping/models.go
  fwprovider/nodes/hardwaremapping/resource_dir.go
  fwprovider/nodes/hardwaremapping/resource_hardware_mapping_test.go
  fwprovider/provider.go
  fwprovider/test/resource_vm_test.go
  fwprovider/types/hardwaremapping/path.go
  main.go
  proxmox/cluster/mapping/types.go
  proxmox/types/hardwaremapping/map.go
  proxmox/types/hardwaremapping/type.go
Labels: size/XXL

#1912 misc(docs): update disclaimer section
  README.md
Labels: autoapprove, size/XS

#1914 fix(vm): cloned VM may be recreated/updated on re-apply
  proxmoxtf/resource/vm/network/schema.go
  proxmoxtf/resource/vm/vm.go
Labels: autoapprove, size/S

#1916 chore(docs): fix broken links in documentation
  docs/index.md
Labels: autoapprove, size/XS

#1917 chore(code): move `hardwaremapping` package from `node` to `cluster` in `fwprovider`
  fwprovider/cluster/hardwaremapping/datasource.go
  fwprovider/cluster/hardwaremapping/datasource_dir.go
  fwprovider/cluster/hardwaremapping/datasource_pci.go
  fwprovider/cluster/hardwaremapping/datasource_usb.go
  fwprovider/cluster/hardwaremapping/errors.go
  fwprovider/cluster/hardwaremapping/models.go
  fwprovider/cluster/hardwaremapping/resource_dir.go
  fwprovider/cluster/hardwaremapping/resource_hardware_mapping_test.go
  fwprovider/cluster/hardwaremapping/resource_pci.go
  fwprovider/cluster/hardwaremapping/resource_usb.go
  fwprovider/cluster/hardwaremapping/shared.go
  fwprovider/provider.go
Labels: autoapprove, size/XS

#1923 fix(file): better error message on download failure
  docs/resources/virtual_environment_download_file.md
  fwprovider/nodes/resource_download_file.go
  fwprovider/nodes/resource_download_file_test.go
  proxmox/nodes/query_url_metadata.go
  proxmox/nodes/query_url_metadata_types.go
Labels: autoapprove, size/S

#1932 fix(container): do not reboot for cpu block changes
  proxmoxtf/resource/container/container.go
Labels: size/XS

#1933 misc(docs): update sponsors
  README.md
Labels: autoapprove, size/XS

#1934 chore(code): fix code problems reported by Qodana
  proxmox/nodes/vms/custom_storage_device.go
  proxmox/nodes/vms/custom_virtiofs_share.go
  proxmoxtf/resource/vm/vm.go
  proxmoxtf/resource/vm/vm_test.go
Labels: autoapprove, size/M

#1939 feat(lxc): increase number of supported mount points to 256
  fwprovider/test/resource_container_test.go
  proxmox/nodes/containers/containers_types.go
  proxmox/nodes/vms/vms_types.go
  proxmoxtf/resource/container/container.go
  utils/maps.go
  utils/maps_test.go
Labels: autoapprove, size/XL
