Repository bpg/terraform-provider-proxmox, pull requests merged in 2025-02, with the labels that each got.

#1737 fix(lxc): allow container disk size 0 for lxc zfs/brfs subvols
  docs/resources/virtual_environment_container.md
  proxmoxtf/resource/container/container.go
Labels: size/XS

#1719 feat(cluster): add `proxmox_virtual_environment_metrics_server` resource
  README.md
  docs/data-sources/virtual_environment_metrics_server.md
  docs/resources/virtual_environment_metrics_server.md
  example/data_source_virtual_environment_metrics_server.tf
  example/resource_virtual_environment_metrics_server.tf
  examples/data-sources/proxmox_virtual_environment_metrics_server/data-source.tf
  examples/resources/proxmox_virtual_environment_metrics_server/import.sh
  examples/resources/proxmox_virtual_environment_metrics_server/resource.tf
  fwprovider/cluster/metrics/datasource_metrics_server.go
  fwprovider/cluster/metrics/metrics_server_model.go
  fwprovider/cluster/metrics/resource_metrics_server.go
  fwprovider/cluster/metrics/resource_metrics_server_test.go
  fwprovider/provider.go
  proxmox/cluster/client.go
  proxmox/cluster/metrics/client.go
  proxmox/cluster/metrics/server.go
  proxmox/cluster/metrics/server_types.go
  tools/tools.go
Labels: size/XXL

#1746 feat(vm): deprecate `enabled` attribute on `cdrom`/`disk` devices
  docs/resources/virtual_environment_vm.md
  example/resource_virtual_environment_vm.tf
  fwprovider/test/resource_vm_cdrom_test.go
  proxmox/nodes/vms/custom_storage_device.go
  proxmox/nodes/vms/custom_storage_device_test.go
  proxmox/nodes/vms/vms_types.go
  proxmoxtf/resource/vm/disk/disk.go
  proxmoxtf/resource/vm/vm.go
Labels: autoapprove, size/L

#1752 fix(file): fix for datastore does not support content type "dump"
  docs/resources/virtual_environment_file.md
  proxmoxtf/resource/file.go
  proxmoxtf/resource/validators/file.go
Labels: size/S

#1755 misc(provider): add missing acc tests
  fwprovider/provider_test.go
Labels: autoapprove, size/S

#1756 chore(docs): update project documentation and contribution guidelines
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  docs/index.md
Labels: autoapprove, size/L

#1759 fix(docs): update incorrect reference to meta_data_file_id
  docs/guides/cloud-init.md
  templates/guides/cloud-init.md.tmpl
Labels: size/S

#1761 chore(docs): reorganize API token auth section
  docs/index.md
Labels: autoapprove, size/L

#1750 feat(lxc): add container datasource
  docs/data-sources/virtual_environment_container.md
  example/data_source_virtual_environment_container.tf
  proxmoxtf/datasource/container.go
  proxmoxtf/datasource/container_test.go
  proxmoxtf/datasource/vm.go
  proxmoxtf/provider/datasources.go
Labels: size/L

#1775 chore(code): update linters config
  .golangci.yml
Labels: autoapprove, size/XS

#1776 chore(docs): remove broken links from SECURITY.md
  .github/SECURITY.md
Labels: autoapprove, size/XS

#1777 feat(vm): add optional `reboot_after_update` configuration flag
  docs/resources/virtual_environment_vm.md
  proxmoxtf/resource/vm/vm.go
Labels: autoapprove, size/S

#1789 chore(build): update Go version and linter /documentation workflows
  .github/renovate.json5
  .github/workflows/golangci-lint.yml
  CONTRIBUTING.md
  Makefile
  README.md
  docs/index.md
  fwprovider/test/test_environment.go
  fwprovider/types/hardwaremapping/path_test.go
  fwprovider/types/ip_addr_test.go
  fwprovider/types/ip_cidr_test.go
  fwprovider/types/nodes/apt/standard_repo_handle_test.go
  go.mod
  go.sum
  main.go
  proxmox/api/client_test.go
  tools/go.mod
  tools/go.sum
  tools/tools.go
  utils/io_test.go
Labels: autoapprove, size/L
