Repository bpg/terraform-provider-proxmox, pull requests merged in 2025-01, with the labels that each got.

#1698 chore(docs): update README.md
  README.md
Labels: autoapprove, size/XS

#1705 chore(docs): add 'stop_on_destroy' configuration to cloud image examples
  docs/guides/cloud-image.md
  examples/guides/cloud-image/centos-qcow2/main.tf
  examples/guides/cloud-image/debian-from-storage/main.tf
  examples/guides/cloud-image/ubuntu-img/main.tf
Labels: autoapprove, size/S

#1707 chore(docs): update README.md
  README.md
Labels: autoapprove, size/XS

#1706 feat(lxc): add support for `device_passthrough` config option
  docs/resources/virtual_environment_container.md
  fwprovider/test/resource_container_test.go
  proxmox/nodes/containers/containers_types.go
  proxmoxtf/resource/container/container.go
  proxmoxtf/resource/container/container_test.go
Labels: size/XL

#1715 fix(vm): handle PVE node availability in VM datasource
  proxmoxtf/datasource/vms.go
Labels: autoapprove, size/S

#1725 chore(testacc): update apt repository acceptance tests
  fwprovider/nodes/apt/repo_test.go
  fwprovider/test/resource_container_test.go
Labels: autoapprove, size/L

#1723 chore(testacc): add missing acceptance build tags, improve vscode settings
  .gitignore
  .vscode/settings.example.json
  .vscode/settings.json
  CONTRIBUTING.md
  fwprovider/network/resource_linux_vlan_test.go
  fwprovider/provider_test.go
  fwprovider/test/resource_vm_test.go
  fwprovider/vm/concurrency_test.go
Labels: size/L

#1722 fix(lxc): support `device_passthrough` config on non-clone container
  fwprovider/test/resource_container_test.go
  proxmoxtf/resource/container/container.go
Labels: size/M

#1732 fix(vm): `vga` block defaults handling during create / clone
  .gitignore
  .vscode/launch.json
  .vscode/settings.example.json
  fwprovider/nodes/apt/repo_test.go
  fwprovider/test/resource_vm_test.go
  proxmoxtf/resource/vm/vm.go
Labels: autoapprove, size/L
