Repository bpg/terraform-provider-proxmox, pull requests merged in 2025-03, with the labels that each got.

#1798 fix(vm): fix vm machine type validation in order to support viommu
  docs/resources/virtual_environment_vm.md
  proxmoxtf/resource/vm/validators.go
  proxmoxtf/resource/vm/validators_test.go
Labels: size/XS

#1803 chore(docs): update sponsorship section
  README.md
Labels: autoapprove, size/XS

#1820 misc(dev): update Makefile
  Makefile
Labels: autoapprove, size/XS

#1824 fix(provider): better error handling for non-existent resources
  README.md
  docs/resources/virtual_environment_vm.md
  fwprovider/test/resource_vm_test.go
  proxmox/api/client.go
Labels: autoapprove, size/M

#1840 fix(vm): fix and improve disk management for cloned VMs
  example/variables.tf
  fwprovider/test/resource_vm_test.go
  fwprovider/vm/resource.go
  proxmox/helpers/ptr/ptr.go
  proxmox/nodes/vms/custom_storage_device.go
  proxmoxtf/resource/vm/disk/disk.go
  proxmoxtf/resource/vm/vm.go
Labels: autoapprove, size/L

#1841 chore(ci): enable attestation
  .github/workflows/publish.yml
  .goreleaser.yaml
Labels: autoapprove, size/S

#1842 chore(docs): update project badges
  README.md
Labels: autoapprove, size/XS

#1848 misc(ci): fix renovate annotations
  .github/workflows/golangci-lint.yml
  Makefile
Labels: autoapprove, size/XS

#1849 fix(vm): handle update of disks moved during VM clone
  .github/workflows/golangci-lint.yml
  Makefile
  fwprovider/test/resource_vm_disks_test.go
  fwprovider/test/resource_vm_test.go
  proxmox/nodes/vms/custom_storage_device.go
  proxmoxtf/provider/provider.go
  proxmoxtf/resource/vm/disk/disk.go
Labels: autoapprove, size/L

#1850 chore(docs)!: clarify disk behaviour in clone operation
  docs/resources/virtual_environment_vm.md
  proxmox/nodes/vms/custom_storage_device.go
Labels: autoapprove, size/S

#1851 fix(docs): clarify `tags` behaviour for container
  docs/resources/virtual_environment_container.md
Labels: :book: documentation, size/XS, automerge

#1854 misc(docs): minor README updates
  README.md
Labels: autoapprove, size/XS

#1855 chore(docs): add known issue for HA VMs and containers in README
  README.md
Labels: autoapprove, size/XS

#1857 fix(token): do not reset user token value in TF state during update
  fwprovider/access/resource_user_test.go
  fwprovider/access/resource_user_token.go
Labels: autoapprove, size/S

#1858 fix(vm): improve error handling when updating `initialization` block
  proxmoxtf/resource/vm/vm.go
Labels: autoapprove, size/S

#1859 fix(lxc): prevent spurious `dns` config change when updating `initialization` block
  docs/resources/virtual_environment_container.md
  fwprovider/test/resource_container_test.go
  proxmox/nodes/containers/containers.go
  proxmox/nodes/containers/containers_types.go
  proxmoxtf/resource/container/container.go
Labels: autoapprove, size/L

#1862 fix(vm): remove `qcow2` as the default for `disk.file_format`
  docs/guides/clone-vm.md
  docs/resources/virtual_environment_vm.md
  example/resource_virtual_environment_vm.tf
  examples/guides/clone-vm/template.tf
  fwprovider/test/resource_vm_disks_test.go
  proxmoxtf/resource/vm/disk/disk.go
  proxmoxtf/resource/vm/disk/schema.go
Labels: autoapprove, size/M

#1863 fix(vm): prevent cloud-init username reset to `" "` during create
  fwprovider/test/resource_vm_test.go
  proxmoxtf/resource/vm/vm.go
Labels: autoapprove, size/S

#1864 fix(vm): prevent cloud-init password reset to `**********` during update
  fwprovider/test/resource_vm_test.go
  proxmoxtf/resource/vm/vm.go
Labels: autoapprove, size/M

#1865 fix(vm): allow to set `machine` type in clone
  fwprovider/test/resource_vm_test.go
  proxmoxtf/resource/vm/vm.go
Labels: autoapprove, size/M

#1866 misc(code): move fwprovider files around
  fwprovider/cluster/acme/datasource_acme_account.go
  fwprovider/cluster/acme/datasource_acme_accounts.go
  fwprovider/cluster/acme/datasource_acme_plugin.go
  fwprovider/cluster/acme/datasource_acme_plugins.go
  fwprovider/cluster/acme/plugin_model.go
  fwprovider/cluster/acme/resource_acme_account.go
  fwprovider/cluster/acme/resource_acme_dns_plugin.go
  fwprovider/cluster/ha/datasource_hagroup.go
  fwprovider/cluster/ha/datasource_hagroups.go
  fwprovider/cluster/ha/datasource_haresource.go
  fwprovider/cluster/ha/datasource_haresources.go
  fwprovider/cluster/ha/hagroup_model.go
  fwprovider/cluster/ha/haresource_model.go
  fwprovider/cluster/ha/resource_hagroup.go
  fwprovider/cluster/ha/resource_haresource.go
  fwprovider/cluster/ha/validators.go
  fwprovider/cluster/options/resource_options.go
  fwprovider/cluster/options/resource_options_test.go
  fwprovider/nodes/hardwaremapping/datasource.go
  fwprovider/nodes/hardwaremapping/datasource_pci.go
  fwprovider/nodes/hardwaremapping/datasource_usb.go
  fwprovider/nodes/hardwaremapping/errors.go
  fwprovider/nodes/hardwaremapping/models.go
  fwprovider/nodes/hardwaremapping/resource_hardware_mapping_test.go
  fwprovider/nodes/hardwaremapping/resource_pci.go
  fwprovider/nodes/hardwaremapping/resource_usb.go
  fwprovider/nodes/hardwaremapping/shared.go
  fwprovider/nodes/network/resource_linux_bridge.go
  fwprovider/nodes/network/resource_linux_bridge_test.go
  fwprovider/nodes/network/resource_linux_vlan.go
  fwprovider/nodes/network/resource_linux_vlan_test.go
  fwprovider/nodes/resource_download_file.go
  fwprovider/nodes/resource_download_file_test.go
  fwprovider/nodes/vm/cdrom/model.go
  fwprovider/nodes/vm/cdrom/resource.go
  fwprovider/nodes/vm/cdrom/resource_schema.go
  fwprovider/nodes/vm/cdrom/resource_test.go
  fwprovider/nodes/vm/concurrency_test.go
  fwprovider/nodes/vm/cpu/datasource_schema.go
  fwprovider/nodes/vm/cpu/model.go
  fwprovider/nodes/vm/cpu/resource.go
  fwprovider/nodes/vm/cpu/resource_schema.go
  fwprovider/nodes/vm/cpu/resource_test.go
  fwprovider/nodes/vm/datasource.go
  fwprovider/nodes/vm/datasource_schema.go
  fwprovider/nodes/vm/model.go
  fwprovider/nodes/vm/resource.go
  fwprovider/nodes/vm/resource_schema.go
  fwprovider/nodes/vm/resource_test.go
  fwprovider/nodes/vm/rng/datasource_schema.go
  fwprovider/nodes/vm/rng/model.go
  fwprovider/nodes/vm/rng/resource.go
  fwprovider/nodes/vm/rng/resource_schema.go
  fwprovider/nodes/vm/rng/resource_test.go
  fwprovider/nodes/vm/vga/datasource_schema.go
  fwprovider/nodes/vm/vga/model.go
  fwprovider/nodes/vm/vga/resource.go
  fwprovider/nodes/vm/vga/resource_schema.go
  fwprovider/nodes/vm/vga/resource_test.go
  fwprovider/provider.go
Labels: autoapprove, size/M

#1867 fix(lxc): multiple issues during container import
  fwprovider/test/resource_container_test.go
  proxmoxtf/resource/container/container.go
Labels: size/S, automerge
