Repository bpg/terraform-provider-proxmox, pull requests merged in 2025-09, with the labels that each got.

#2151 fix(ci): update link checker config
  .github/workflows/link-check.yml
  .lycheeignore
  lychee.toml
Labels: size/S

#2156 chore(code): minor code cleanups
  .golangci.yml
  fwprovider/cluster/acme/datasource_acme_plugin_test.go
  fwprovider/cluster/sdn/applier/resource.go
  proxmox/cluster/firewall/options_types.go
  proxmox/cluster/sdn/zones/doc.go
  proxmox/helpers/ptr/ptr.go
  proxmox/nodes/containers/containers_types.go
  proxmox/nodes/vms/custom_agent.go
  proxmox/nodes/vms/custom_amdsev.go
  proxmox/nodes/vms/custom_cpu_emulation.go
  proxmox/nodes/vms/custom_efi_disk.go
  proxmox/nodes/vms/custom_network_device.go
  proxmox/nodes/vms/custom_numa_device.go
  proxmox/nodes/vms/custom_pci_device.go
  proxmox/nodes/vms/custom_rng_device.go
  proxmox/nodes/vms/custom_storage_device.go
  proxmox/nodes/vms/custom_usb_device.go
  proxmox/nodes/vms/custom_virtiofs_share.go
Labels: size/L

#2166 chore(docs): include vm/lxc lock error details in the README known issues section
  README.md
Labels: size/XS

#2178 fix(firewall): detect drift when rules are manually deleted
  fwprovider/test/resource_firewall_test.go
  proxmoxtf/resource/firewall/rules.go
  proxmoxtf/resource/firewall/rules_test.go
Labels: size/L

#2204 fix(sdn): subnet validation errors when using value interpolation
  fwprovider/cluster/sdn/subnet/model.go
  fwprovider/cluster/sdn/subnet/resource.go
  fwprovider/cluster/sdn/subnet/resource_test.go
Labels: size/M
