Repository bpg/terraform-provider-proxmox, pull requests merged in 2025-05, with the labels that each got.

#1940 file(file): handle remote file size check error in `download_file` resource
  fwprovider/nodes/resource_download_file.go
  fwprovider/nodes/resource_download_file_test.go
  fwprovider/test/resource_file_test.go
  fwprovider/test/test_support.go
Labels: autoapprove, size/L

#1952 feat(vm): add support for amd-sev parameter
  docs/resources/virtual_environment_vm.md
  proxmox/nodes/vms/custom_amdsev.go
  proxmox/nodes/vms/vms_types.go
  proxmoxtf/resource/vm/validators.go
  proxmoxtf/resource/vm/vm.go
Labels: size/L

#1961 fix(network): adjust Linux Bridge name validator
  docs/resources/virtual_environment_network_linux_bridge.md
  fwprovider/nodes/network/resource_linux_bridge.go
Labels: autoapprove, size/S

#1968 feat(lxc): increase maximum supported passthrough devices to 128
  proxmoxtf/resource/container/container.go
Labels: size/XS

#1971 fix(vm): allow `scsi` and `sata` for CD-ROM interface
  docs/resources/virtual_environment_vm.md
  fwprovider/test/resource_vm_cdrom_test.go
  proxmoxtf/resource/vm/validators.go
  proxmoxtf/resource/vm/vm.go
Labels: autoapprove, size/M
