Repository bpg/terraform-provider-proxmox, pull requests merged in 2025-06, with the labels that each got.

#1991 shore(docs): update API Token auth section
  .devcontainer/Dockerfile
  .markdownlint.json
  CODE_OF_CONDUCT.md
  README.md
  docs/index.md
  docs/resources/virtual_environment_vm.md
Labels: autoapprove, size/M

#1989 fix(file): properly handle overwrite option behavior in `proxmox_virtual_environment_download_file`
  docs/resources/virtual_environment_download_file.md
  fwprovider/nodes/resource_download_file.go
  fwprovider/nodes/resource_download_file_test.go
  fwprovider/test/resource_file_test.go
Labels: size/L

#1994 fix(docs): firewall security group typo `enabled`
  docs/resources/virtual_environment_cluster_firewall_security_group.md
Labels: size/XS

#2000 misc(docs): remove CodeRabbit Pull Request Reviews badge from README.md
  README.md
Labels: autoapprove, size/XS

#2001 fix(network): improve error handling on `create`/`read`/`update`
  fwprovider/nodes/network/resource_linux_bridge.go
  fwprovider/nodes/network/resource_linux_vlan.go
Labels: size/L

#2007 fix(tests): fix `make example` tests
  example/resource_virtual_environment_container.tf
  example/resource_virtual_environment_download_file.tf
  example/resource_virtual_environment_trunks.tf
  example/variables.tf
Labels: autoapprove, size/S
