Repository bpg/terraform-provider-proxmox, pull requests merged in 2025-07, with the labels that each got.

#2014 chore(docs): minor fixes / updates in guides
  docs/guides/cloud-image.md
  docs/guides/cloud-init.md
  examples/guides/cloud-image/debian-from-storage/main.tf
  examples/guides/cloud-init/native/main.tf
Labels: autoapprove, size/S

#2012 feat(vm): Import Disk via API.
  README.md
  docs/guides/cloud-image.md
  docs/guides/cloud-init.md
  docs/index.md
  docs/resources/virtual_environment_vm.md
  example/resource_virtual_environment_vm.tf
  examples/guides/cloud-image/centos-qcow2/main.tf
  examples/guides/cloud-image/centos-qcow2/provider.tf
  examples/guides/cloud-image/debian-from-storage/main.tf
  examples/guides/cloud-image/ubuntu-img/main.tf
  examples/guides/cloud-image/ubuntu-img/provider.tf
  examples/guides/cloud-init/custom/main.tf
  examples/guides/cloud-init/native/main.tf
  examples/guides/cloud-init/native/provider.tf
  fwprovider/test/resource_vm_disks_test.go
  proxmox/nodes/vms/custom_storage_device.go
  proxmoxtf/resource/vm/disk/disk.go
  proxmoxtf/resource/vm/disk/schema.go
  proxmoxtf/resource/vm/disk/schema_test.go
  proxmoxtf/resource/vm/vm.go
Labels: size/L

#2028 feat(provider): add support for ssh `agent_forwarding`
  docs/index.md
  fwprovider/nodes/resource_download_file_test.go
  fwprovider/provider.go
  fwprovider/test/resource_file_test.go
  proxmox/ssh/client.go
  proxmoxtf/provider/provider.go
  proxmoxtf/provider/schema.go
Labels: size/L

#2033 fix(lxc): avoid setting domain to `" "` when null during clone
  fwprovider/test/resource_container_test.go
  proxmoxtf/resource/container/container.go
Labels: autoapprove, size/S

#2043 fix(api): improve API response error handling
  proxmox/api/client.go
  proxmox/api/client_test.go
  proxmox/api/client_types.go
Labels: autoapprove, size/M

#2052 feat(firewall): adds forward type to firewall rules
  docs/resources/virtual_environment_cluster_firewall_security_group.md
  docs/resources/virtual_environment_firewall_rules.md
  proxmoxtf/resource/firewall/rules.go
Labels: size/XS

#2058 chore(project): switch repo infographic to repobeats
  .github/workflows/metrics.yml
  README.md
Labels: autoapprove, size/M

#2063 chore(docs): add ceph squid to `apt_standard_repository` docs
  docs/resources/virtual_environment_apt_standard_repository.md
  fwprovider/nodes/apt/resource_standard_repo.go
Labels: :hourglass: pending author's response, size/XS, automerge
