Repository bpg/terraform-provider-proxmox, pull requests merged in 2025-08, with the labels that each got.

#2072 fix(acme): fix ACME account management & add acceptance tests
  fwprovider/cluster/acme/datasource_acme_account_test.go
  fwprovider/cluster/acme/datasource_acme_accounts_test.go
  fwprovider/cluster/acme/datasource_acme_plugin_test.go
  fwprovider/cluster/acme/datasource_acme_plugins_test.go
  fwprovider/cluster/acme/resource_acme_account.go
  fwprovider/cluster/acme/resource_acme_account_test.go
  fwprovider/cluster/acme/resource_acme_dns_plugin_test.go
Labels: autoapprove, size/XL

#2092 chore(docs): remove spurious sdn datasource .tf examples
  proxmox_virtual_environment_sdn_zone_evpn/data-source.tf
  proxmox_virtual_environment_sdn_zone_qinq/data-source.tf
  proxmox_virtual_environment_sdn_zone_simple/data-source.tf
  proxmox_virtual_environment_sdn_zone_vlan/data-source.tf
  proxmox_virtual_environment_sdn_zone_vxlan/data-source.tf
  proxmox_virtual_environment_sdn_zones/data-source.tf
Labels: autoapprove, size/L

#2088 fix(lxc): adjust max number of container's IP configs
  proxmoxtf/resource/container/container.go
Labels: size/XS

#2067 feat(lxc): Add missing configuration options for container rootfs
  docs/resources/virtual_environment_container.md
  fwprovider/test/resource_container_test.go
  proxmox/nodes/containers/containers_types.go
  proxmoxtf/resource/container/container.go
Labels: size/L

#2114 fix(vm): regression: disk re-ordering on re-apply
  fwprovider/test/resource_vm_disks_test.go
  proxmoxtf/resource/vm/disk/disk.go
  proxmoxtf/resource/vm/disk/disk_test.go
  utils/maps.go
  utils/maps_test.go
Labels: autoapprove, size/L

#2122 fix(vm): prevent re-creation of previously imported disks on update
  fwprovider/test/resource_vm_disks_test.go
  proxmox/nodes/vms/custom_storage_device.go
  proxmoxtf/resource/vm/disk/disk.go
  proxmoxtf/resource/vm/disk/disk_test.go
Labels: size/L

#2127 feat(sdn): added custom resource to apply sdn configurations
  docs/data-sources/virtual_environment_sdn_zone_evpn.md
  docs/data-sources/virtual_environment_sdn_zone_qinq.md
  docs/data-sources/virtual_environment_sdn_zone_simple.md
  docs/data-sources/virtual_environment_sdn_zone_vlan.md
  docs/data-sources/virtual_environment_sdn_zone_vxlan.md
  docs/data-sources/virtual_environment_sdn_zones.md
  docs/resources/virtual_environment_sdn_applier.md
  docs/resources/virtual_environment_sdn_zone_evpn.md
  docs/resources/virtual_environment_sdn_zone_qinq.md
  docs/resources/virtual_environment_sdn_zone_simple.md
  docs/resources/virtual_environment_sdn_zone_vlan.md
  docs/resources/virtual_environment_sdn_zone_vxlan.md
  example/resource_virtual_environment_sdn_applier.tf
  examples/resources/proxmox_virtual_environment_sdn_applier/resource.tf
  fwprovider/cluster/sdn/applier/resource.go
  fwprovider/cluster/sdn/applier/resource_test.go
  fwprovider/cluster/sdn/zone/datasource_generic.go
  fwprovider/cluster/sdn/zone/datasource_zones.go
  fwprovider/cluster/sdn/zone/datasource_zones_test.go
  fwprovider/cluster/sdn/zone/resource_evpn.go
  fwprovider/cluster/sdn/zone/resource_generic.go
  fwprovider/cluster/sdn/zone/resource_qinq.go
  fwprovider/cluster/sdn/zone/resource_vlan.go
  fwprovider/cluster/sdn/zone/resource_vxlan.go
  fwprovider/cluster/sdn/zone/resource_zones_test.go
  fwprovider/provider.go
  go.mod
  main.go
  proxmox/cluster/client.go
  proxmox/cluster/sdn/applier/api.go
  proxmox/cluster/sdn/applier/applier.go
  proxmox/cluster/sdn/applier/applier_types.go
  proxmox/cluster/sdn/applier/client.go
  proxmox/cluster/sdn/zones/zones.go
  proxmox/cluster/sdn/zones/zones_types.go
Labels: size/XXL
